/*
 * PayConductor API
 *
 * PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  - -- -  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |- -- -- -|- -- -- -- -- -- --| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using payconductor-sdk.Model;
using payconductor-sdk.Client;
using System.Reflection;

namespace payconductor-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PostOrders200ResponseOrderItemsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostOrders200ResponseOrderItemsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostOrders200ResponseOrderItemsInner
        //private PostOrders200ResponseOrderItemsInner instance;

        public PostOrders200ResponseOrderItemsInnerTests()
        {
            // TODO uncomment below to create an instance of PostOrders200ResponseOrderItemsInner
            //instance = new PostOrders200ResponseOrderItemsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostOrders200ResponseOrderItemsInner
        /// </summary>
        [Fact]
        public void PostOrders200ResponseOrderItemsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostOrders200ResponseOrderItemsInner
            //Assert.IsType<PostOrders200ResponseOrderItemsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Qty'
        /// </summary>
        [Fact]
        public void QtyTest()
        {
            // TODO unit test for the property 'Qty'
        }

        /// <summary>
        /// Test the property 'TotalAmount'
        /// </summary>
        [Fact]
        public void TotalAmountTest()
        {
            // TODO unit test for the property 'TotalAmount'
        }

        /// <summary>
        /// Test the property 'TotalNetAmount'
        /// </summary>
        [Fact]
        public void TotalNetAmountTest()
        {
            // TODO unit test for the property 'TotalNetAmount'
        }

        /// <summary>
        /// Test the property 'UnityPrice'
        /// </summary>
        [Fact]
        public void UnityPriceTest()
        {
            // TODO unit test for the property 'UnityPrice'
        }

        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
    }
}
