/*
 * PayConductor API
 *
 * PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostOrders200Response {
    /// Order ID in the system
    #[serde(rename = "id")]
    pub id: String,
    /// External order ID (provided by your integration)
    #[serde(rename = "externalId", deserialize_with = "Option::deserialize")]
    pub external_id: Option<String>,
    /// Provider used to process the order
    #[serde(rename = "externalIntegrationKey")]
    pub external_integration_key: String,
    /// Order ID in the payment provider
    #[serde(rename = "externalIntegrationId", deserialize_with = "Option::deserialize")]
    pub external_integration_id: Option<String>,
    /// Total order amount
    #[serde(rename = "amount")]
    pub amount: f64,
    /// Cost fee applied to the order
    #[serde(rename = "costFee")]
    pub cost_fee: f64,
    #[serde(rename = "pix", skip_serializing_if = "Option::is_none")]
    pub pix: Option<Box<models::PostOrders200ResponsePix>>,
    #[serde(rename = "bankSlip", skip_serializing_if = "Option::is_none")]
    pub bank_slip: Option<Box<models::PostOrders200ResponseBankSlip>>,
    #[serde(rename = "nuPay", skip_serializing_if = "Option::is_none")]
    pub nu_pay: Option<Box<models::PostOrders200ResponseNuPay>>,
    #[serde(rename = "picPay", skip_serializing_if = "Option::is_none")]
    pub pic_pay: Option<Box<models::PostOrders200ResponsePicPay>>,
    #[serde(rename = "creditCard", skip_serializing_if = "Option::is_none")]
    pub credit_card: Option<Box<models::PostOrders200ResponseCreditCard>>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "paymentMethod")]
    pub payment_method: PaymentMethod,
    /// Date and time when the order was paid (ISO 8601)
    #[serde(rename = "payedAt", deserialize_with = "Option::deserialize")]
    pub payed_at: Option<String>,
    /// Error code, if any
    #[serde(rename = "errorCode", deserialize_with = "Option::deserialize")]
    pub error_code: Option<String>,
    /// Error message, if any
    #[serde(rename = "errorMessage", deserialize_with = "Option::deserialize")]
    pub error_message: Option<String>,
    #[serde(rename = "orderItems")]
    pub order_items: Vec<models::PostOrders200ResponseOrderItemsInner>,
    #[serde(rename = "session", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub session: Option<Option<Box<models::PostOrders200ResponseSession>>>,
}

impl PostOrders200Response {
    pub fn new(id: String, external_id: Option<String>, external_integration_key: String, external_integration_id: Option<String>, amount: f64, cost_fee: f64, status: Status, payment_method: PaymentMethod, payed_at: Option<String>, error_code: Option<String>, error_message: Option<String>, order_items: Vec<models::PostOrders200ResponseOrderItemsInner>) -> PostOrders200Response {
        PostOrders200Response {
            id,
            external_id,
            external_integration_key,
            external_integration_id,
            amount,
            cost_fee,
            pix: None,
            bank_slip: None,
            nu_pay: None,
            pic_pay: None,
            credit_card: None,
            status,
            payment_method,
            payed_at,
            error_code,
            error_message,
            order_items,
            session: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Generating")]
    Generating,
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "Failed")]
    Failed,
    #[serde(rename = "Canceled")]
    Canceled,
    #[serde(rename = "Refunding")]
    Refunding,
    #[serde(rename = "Refunded")]
    Refunded,
    #[serde(rename = "InDispute")]
    InDispute,
    #[serde(rename = "Chargeback")]
    Chargeback,
}

impl Default for Status {
    fn default() -> Status {
        Self::Generating
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentMethod {
    #[serde(rename = "Pix")]
    Pix,
    #[serde(rename = "CreditCard")]
    CreditCard,
    #[serde(rename = "DebitCard")]
    DebitCard,
    #[serde(rename = "BankSlip")]
    BankSlip,
    #[serde(rename = "Crypto")]
    Crypto,
    #[serde(rename = "ApplePay")]
    ApplePay,
    #[serde(rename = "NuPay")]
    NuPay,
    #[serde(rename = "PicPay")]
    PicPay,
    #[serde(rename = "AmazonPay")]
    AmazonPay,
    #[serde(rename = "SepaDebit")]
    SepaDebit,
    #[serde(rename = "GooglePay")]
    GooglePay,
}

impl Default for PaymentMethod {
    fn default() -> PaymentMethod {
        Self::Pix
    }
}

