/*
 * PayConductor API
 *
 * PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostOrdersRequestSession : If externalSessionId or sessionId is provided and an existing session exists, it will be updated with the new data. Otherwise, a new session will be created.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostOrdersRequestSession {
    /// Time in minutes for checkout session expiration
    #[serde(rename = "expiresInMinutes", skip_serializing_if = "Option::is_none")]
    pub expires_in_minutes: Option<f64>,
    /// Checkout URL for redirection
    #[serde(rename = "checkoutUrl", skip_serializing_if = "Option::is_none")]
    pub checkout_url: Option<String>,
    /// ID generated by our service to identify the checkout session
    #[serde(rename = "sessionId", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    /// Checkout session ID generated by the client side. The ID must be unique for each cart session
    #[serde(rename = "externalSessionId", skip_serializing_if = "Option::is_none")]
    pub external_session_id: Option<String>,
}

impl PostOrdersRequestSession {
    /// If externalSessionId or sessionId is provided and an existing session exists, it will be updated with the new data. Otherwise, a new session will be created.
    pub fn new() -> PostOrdersRequestSession {
        PostOrdersRequestSession {
            expires_in_minutes: None,
            checkout_url: None,
            session_id: None,
            external_session_id: None,
        }
    }
}

