/*
 * PayConductor API
 *
 * # Introdução  Esta documentação cobre todas as funcionalidades disponíveis na API RESTful do PayConductor, incluindo autenticação, gerenciamento de recursos e exemplos de uso.  <br />  <br />  ----  <br />   # Autenticação  A API do PayConductor utiliza autenticação HTTP Basic para validar requisições. Você precisa fornecer suas credenciais (Client ID e Client Secret) no formato `client:secret` codificado em Base64.  <br />  ## Obtendo Credenciais  1. Acesse o painel administrativo do PayConductor 2. Navegue até **Configurações > API Keys** 3. Gere um novo par de credenciais (Client ID e Client Secret) 4. Guarde o Client Secret em local seguro - ele não será exibido novamente  <br />  ## Formato de Autenticação  As credenciais devem ser enviadas no header `Authorization` usando o esquema Basic:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Exemplo em Node.js  ```javascript const clientId = 'seu_client_id'; const clientSecret = 'seu_client_secret';  // Codifica as credenciais em Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Erros de Autenticação  | Código | Descrição | |--------|-----------| | `401`  | Credenciais inválidas ou ausentes | | `403`  | Credenciais válidas, mas sem permissão para o recurso | | `429`  | Muitas requisições (rate limit excedido) |  ### Exemplo de resposta de erro  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostWithdraws200Response {
    /// Identificador único do saque
    #[serde(rename = "id")]
    pub id: String,
    /// ID do saque no sistema no seu sistema
    #[serde(rename = "externalId", deserialize_with = "Option::deserialize")]
    pub external_id: Option<String>,
    /// Chave do provedor utilizado para o saque
    #[serde(rename = "externalIntegrationKey")]
    pub external_integration_key: String,
    /// ID do saque no provedor de pagamento
    #[serde(rename = "externalIntegrationId", deserialize_with = "Option::deserialize")]
    pub external_integration_id: Option<String>,
    /// Taxa de custo aplicada ao saque
    #[serde(rename = "costFee")]
    pub cost_fee: f64,
    /// Status do saque
    #[serde(rename = "status")]
    pub status: Status,
    /// Código do erro, se houver
    #[serde(rename = "errorCode", deserialize_with = "Option::deserialize")]
    pub error_code: Option<String>,
    /// Mensagem descritiva do erro, se houver
    #[serde(rename = "errorMessage", deserialize_with = "Option::deserialize")]
    pub error_message: Option<String>,
    #[serde(rename = "payedAt", deserialize_with = "Option::deserialize")]
    pub payed_at: Option<Box<models::PostWithdraws200ResponsePayedAt>>,
    #[serde(rename = "payoutAccount")]
    pub payout_account: Box<models::PostWithdraws200ResponsePayoutAccount>,
}

impl PostWithdraws200Response {
    pub fn new(id: String, external_id: Option<String>, external_integration_key: String, external_integration_id: Option<String>, cost_fee: f64, status: Status, error_code: Option<String>, error_message: Option<String>, payed_at: Option<models::PostWithdraws200ResponsePayedAt>, payout_account: models::PostWithdraws200ResponsePayoutAccount) -> PostWithdraws200Response {
        PostWithdraws200Response {
            id,
            external_id,
            external_integration_key,
            external_integration_id,
            cost_fee,
            status,
            error_code,
            error_message,
            payed_at: if let Some(x) = payed_at {Some(Box::new(x))} else {None},
            payout_account: Box::new(payout_account),
        }
    }
}
/// Status do saque
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Transferring")]
    Transferring,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "Failed")]
    Failed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Pending
    }
}

