#' PayConductor API
#'
#' PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
#'
#' The version of the OpenAPI document: 1.0.0
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Orders operations
#' @description OrdersApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  GetOrders  ####################
#'
#' library(payconductor-sdk)
#' var_period <- "Last7Days" # character | 
#' var_page <- 1 # numeric | 
#' var_page_size <- 20 # numeric | 
#' var_end_date <- "end_date_example" # character |  (Optional)
#' var_start_date <- "start_date_example" # character |  (Optional)
#' var_id <- "id_example" # character |  (Optional)
#' var_status <- "status_example" # character |  (Optional)
#'
#' #List orders
#' api_instance <- OrdersApi$new()
#'
#' # Configure HTTP basic authorization: basicAuth
#' api_instance$api_client$username <- Sys.getenv("USERNAME")
#' api_instance$api_client$password <- Sys.getenv("PASSWORD")
#'
#' api_instance$GetOrders(var_period, var_page, var_page_size, end_date = var_end_date, start_date = var_start_date, id = var_id, status = var_status)
#'
#'
#' ####################  GetOrdersById  ####################
#'
#' library(payconductor-sdk)
#' var_id <- "id_example" # character | 
#'
#' #Get order by ID
#' api_instance <- OrdersApi$new()
#'
#' # Configure HTTP basic authorization: basicAuth
#' api_instance$api_client$username <- Sys.getenv("USERNAME")
#' api_instance$api_client$password <- Sys.getenv("PASSWORD")
#'
#' api_instance$GetOrdersById(var_id)
#'
#'
#' ####################  PostOrders  ####################
#'
#' library(payconductor-sdk)
#' var_post_orders_request <- postOrders_request$new(123, "clientIp_example", Customer$new("documentNumber_example", "Cpf", "email_example", "name_example", Customer_address$new("city_example", "country_example", "neighborhood_example", "number_example", "state_example", "street_example", "zipCode_example"), "phoneNumber_example"), 123, "externalId_example", postOrders_request_payment$new("paymentMethod_example", Credit_Card_card$new("token_example", "cvv_example", Complete_card_data_expiration$new(123, 123), "holderName_example", "number_example", "firstSixCardNumber_example"), Credit_Card_installments$new(), NuPay_nuPay$new("cancelUrl_example", "merchantName_example", "returnUrl_example", "storeName_example"), Pix_expirationInSeconds$new(), "softDescriptor_example", Bank_Slip_expirationInDays$new()), 123, 123, postOrders_request_fingerprints$new("threatMetrixFingerprintId_example"), c(postOrders_request_items_inner$new("id_example", "isPhysical_example", "name_example", 123, 123)), MerchantInput$new("document_example", "email_example", "name_example"), 123, postOrders_request_session$new(123, "checkoutUrl_example", "sessionId_example", "externalSessionId_example"), 123) # PostOrdersRequest | 
#'
#' #Create order
#' api_instance <- OrdersApi$new()
#'
#' # Configure HTTP basic authorization: basicAuth
#' api_instance$api_client$username <- Sys.getenv("USERNAME")
#' api_instance$api_client$password <- Sys.getenv("PASSWORD")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$PostOrders(var_post_orders_requestdata_file = "result.txt")
#' result <- api_instance$PostOrders(var_post_orders_request)
#' dput(result)
#'
#'
#' ####################  PostOrdersByIdRefund  ####################
#'
#' library(payconductor-sdk)
#' var_id <- "id_example" # character | 
#'
#' #Refund order
#' api_instance <- OrdersApi$new()
#'
#' # Configure HTTP basic authorization: basicAuth
#' api_instance$api_client$username <- Sys.getenv("USERNAME")
#' api_instance$api_client$password <- Sys.getenv("PASSWORD")
#'
#' api_instance$PostOrdersByIdRefund(var_id)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
OrdersApi <- R6::R6Class(
  "OrdersApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new OrdersApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' List orders
    #'
    #' @param period 
    #' @param page 
    #' @param page_size 
    #' @param end_date (optional) No description
    #' @param start_date (optional) No description
    #' @param id (optional) No description
    #' @param status (optional) No description
    #' @param ... Other optional arguments
    #'
    #' @return void
    GetOrders = function(period, page, page_size, end_date = NULL, start_date = NULL, id = NULL, status = NULL, ...) {
      local_var_response <- self$GetOrdersWithHttpInfo(period, page, page_size, end_date, start_date, id, status, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' List orders
    #'
    #' @param period 
    #' @param page 
    #' @param page_size 
    #' @param end_date (optional) No description
    #' @param start_date (optional) No description
    #' @param id (optional) No description
    #' @param status (optional) No description
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    GetOrdersWithHttpInfo = function(period, page, page_size, end_date = NULL, start_date = NULL, id = NULL, status = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`period`)) {
        stop("Missing required parameter `period`.")
      }

      if (missing(`page`)) {
        stop("Missing required parameter `page`.")
      }

      if (missing(`page_size`)) {
        stop("Missing required parameter `page_size`.")
      }

      if (!missing(`period`) && is.null(`period`)) {
        stop("Invalid value for `period` when calling OrdersApi$GetOrders, `period` is not nullable")
      }

      if (!missing(`page`) && is.null(`page`)) {
        stop("Invalid value for `page` when calling OrdersApi$GetOrders, `page` is not nullable")
      }
      if (!is.null(`page`) && `page` <  1) {
        stop("Invalid value for `page` when calling OrdersApi$GetOrders, must be bigger than or equal to 1.")
      }

      if (!missing(`page_size`) && is.null(`page_size`)) {
        stop("Invalid value for `page_size` when calling OrdersApi$GetOrders, `page_size` is not nullable")
      }
      if (!is.null(`page_size`) && `page_size` >  100) {
        stop("Invalid value for `page_size` when calling OrdersApi$GetOrders, must be smaller than or equal to 100.")
      }
      if (!is.null(`page_size`) && `page_size` <  1) {
        stop("Invalid value for `page_size` when calling OrdersApi$GetOrders, must be bigger than or equal to 1.")
      }

      if (!missing(`end_date`) && is.null(`end_date`)) {
        stop("Invalid value for `end_date` when calling OrdersApi$GetOrders, `end_date` is not nullable")
      }

      if (!missing(`start_date`) && is.null(`start_date`)) {
        stop("Invalid value for `start_date` when calling OrdersApi$GetOrders, `start_date` is not nullable")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling OrdersApi$GetOrders, `id` is not nullable")
      }

      if (!missing(`status`) && is.null(`status`)) {
        stop("Invalid value for `status` when calling OrdersApi$GetOrders, `status` is not nullable")
      }

      if (!is.null(`period`) && !(`period` %in% c("Today", "Yesterday", "Last7Days", "Last30Days", "ThisMonth", "LastMonth", "ThisYear", "Custom"))) {
        stop("Invalid value for period when calling OrdersApi$GetOrders. Must be [Today, Yesterday, Last7Days, Last30Days, ThisMonth, LastMonth, ThisYear, Custom].")
      }
      query_params[["period"]] <- `period`

      query_params[["endDate"]] <- `end_date`

      query_params[["startDate"]] <- `start_date`

      query_params[["page"]] <- `page`

      query_params[["pageSize"]] <- `page_size`

      query_params[["id"]] <- `id`

      if (!is.null(`status`) && !(`status` %in% c("Generating", "Pending", "Completed", "Failed", "Canceled", "Refunding", "Refunded", "InDispute", "Chargeback"))) {
        stop("Invalid value for status when calling OrdersApi$GetOrders. Must be [Generating, Pending, Completed, Failed, Canceled, Refunding, Refunded, InDispute, Chargeback].")
      }
      query_params[["status"]] <- `status`

      local_var_url_path <- "/orders/"
      # HTTP basic auth
      if (!is.null(self$api_client$username) || !is.null(self$api_client$password)) {
        header_params["Authorization"] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$api_client$username, self$api_client$password, sep = ":"))))
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Get order by ID
    #'
    #' @param id 
    #' @param ... Other optional arguments
    #'
    #' @return void
    GetOrdersById = function(id, ...) {
      local_var_response <- self$GetOrdersByIdWithHttpInfo(id, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Get order by ID
    #'
    #' @param id 
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    GetOrdersByIdWithHttpInfo = function(id, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling OrdersApi$GetOrdersById, `id` is not nullable")
      }

      local_var_url_path <- "/orders/{id}"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # HTTP basic auth
      if (!is.null(self$api_client$username) || !is.null(self$api_client$password)) {
        header_params["Authorization"] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$api_client$username, self$api_client$password, sep = ":"))))
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Create order
    #'
    #' @param post_orders_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return PostOrders200Response
    PostOrders = function(post_orders_request, data_file = NULL, ..., .parse = TRUE) {
      local_var_response <- self$PostOrdersWithHttpInfo(post_orders_request, data_file = data_file, ..., .parse = .parse)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Create order
    #'
    #' @param post_orders_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @param .parse Logical. If \code{TRUE} then the response will be parsed to a generated type. If \code{FALSE} the response will be returned as unparsed text.
    #'
    #' @return API response (PostOrders200Response) with additional information such as HTTP status code, headers
    PostOrdersWithHttpInfo = function(post_orders_request, data_file = NULL, ..., .parse = TRUE) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`post_orders_request`)) {
        stop("Missing required parameter `post_orders_request`.")
      }

      if (!missing(`post_orders_request`) && is.null(`post_orders_request`)) {
        stop("Invalid value for `post_orders_request` when calling OrdersApi$PostOrders, `post_orders_request` is not nullable")
      }

      if (!is.null(`post_orders_request`)) {
        local_var_body <- `post_orders_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/orders/"
      # HTTP basic auth
      if (!is.null(self$api_client$username) || !is.null(self$api_client$password)) {
        header_params["Authorization"] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$api_client$username, self$api_client$password, sep = ":"))))
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }
        if (!.parse) {
          local_var_resp$content <- local_var_resp$response_as_text()
          return(local_var_resp)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "PostOrders200Response"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Refund order
    #'
    #' @param id 
    #' @param ... Other optional arguments
    #'
    #' @return void
    PostOrdersByIdRefund = function(id, ...) {
      local_var_response <- self$PostOrdersByIdRefundWithHttpInfo(id, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Refund order
    #'
    #' @param id 
    #' @param ... Other optional arguments
    #'
    #' @return API response (void) with additional information such as HTTP status code, headers
    PostOrdersByIdRefundWithHttpInfo = function(id, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`id`) && is.null(`id`)) {
        stop("Invalid value for `id` when calling OrdersApi$PostOrdersByIdRefund, `id` is not nullable")
      }

      local_var_url_path <- "/orders/{id}/refund"
      if (!missing(`id`)) {
        local_var_url_path <- gsub("\\{id\\}", URLencode(as.character(`id`), reserved = TRUE), local_var_url_path)
      }

      # HTTP basic auth
      if (!is.null(self$api_client$username) || !is.null(self$api_client$password)) {
        header_params["Authorization"] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$api_client$username, self$api_client$password, sep = ":"))))
      }

      # The Accept request HTTP header
      local_var_accepts <- list()

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        local_var_resp$content <- NULL
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(content = paste("Server returned ", local_var_resp$status_code, " response status code."),
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new(content = "API client error",
                        response = local_var_resp,
                        status_code = local_var_resp$status_code)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || all(local_var_resp$response == "")) {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
