/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package payconductor-sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import payconductor-sdk.apis.OrdersApi
import payconductor-sdk.models.PostOrders200Response
import payconductor-sdk.models.PostOrdersRequest

class OrdersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrdersApi
        //val apiInstance = OrdersApi()

        // to test getOrders
        should("test getOrders") {
            // uncomment below to test getOrders
            //val period : kotlin.String = period_example // kotlin.String | 
            //val page : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val pageSize : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val endDate : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val startDate : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val status : kotlin.String = status_example // kotlin.String | 
            //apiInstance.getOrders(period, page, pageSize, endDate, startDate, id, status)
        }

        // to test getOrdersById
        should("test getOrdersById") {
            // uncomment below to test getOrdersById
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.getOrdersById(id)
        }

        // to test postOrders
        should("test postOrders") {
            // uncomment below to test postOrders
            //val postOrdersRequest : PostOrdersRequest =  // PostOrdersRequest | 
            //val result : PostOrders200Response = apiInstance.postOrders(postOrdersRequest)
            //result shouldBe ("TODO")
        }

        // to test postOrdersByIdRefund
        should("test postOrdersByIdRefund") {
            // uncomment below to test postOrdersByIdRefund
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.postOrdersByIdRefund(id)
        }

    }
}
