/*
 * PayConductor API
 * PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Customer;
import org.openapitools.client.model.MerchantInput;
import org.openapitools.client.model.PostOrdersRequestFingerprints;
import org.openapitools.client.model.PostOrdersRequestItemsInner;
import org.openapitools.client.model.PostOrdersRequestPayment;
import org.openapitools.client.model.PostOrdersRequestSession;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PostOrdersRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-18T15:58:14.340077800-03:00[America/Bahia]", comments = "Generator version: 7.20.0")
public class PostOrdersRequest {
  public static final String SERIALIZED_NAME_CHARGE_AMOUNT = "chargeAmount";
  @SerializedName(SERIALIZED_NAME_CHARGE_AMOUNT)
  @javax.annotation.Nonnull
  private BigDecimal chargeAmount;

  public static final String SERIALIZED_NAME_CLIENT_IP = "clientIp";
  @SerializedName(SERIALIZED_NAME_CLIENT_IP)
  @javax.annotation.Nonnull
  private String clientIp;

  public static final String SERIALIZED_NAME_CUSTOMER = "customer";
  @SerializedName(SERIALIZED_NAME_CUSTOMER)
  @javax.annotation.Nonnull
  private Customer customer;

  public static final String SERIALIZED_NAME_DISCOUNT_AMOUNT = "discountAmount";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_AMOUNT)
  @javax.annotation.Nonnull
  private BigDecimal discountAmount = new BigDecimal("0");

  public static final String SERIALIZED_NAME_EXTERNAL_ID = "externalId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ID)
  @javax.annotation.Nonnull
  private String externalId;

  public static final String SERIALIZED_NAME_FINGERPRINTS = "fingerprints";
  @SerializedName(SERIALIZED_NAME_FINGERPRINTS)
  @javax.annotation.Nullable
  private PostOrdersRequestFingerprints fingerprints;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  @javax.annotation.Nullable
  private List<PostOrdersRequestItemsInner> items = new ArrayList<>();

  public static final String SERIALIZED_NAME_MERCHANT = "merchant";
  @SerializedName(SERIALIZED_NAME_MERCHANT)
  @javax.annotation.Nullable
  private MerchantInput merchant;

  public static final String SERIALIZED_NAME_PAYMENT = "payment";
  @SerializedName(SERIALIZED_NAME_PAYMENT)
  @javax.annotation.Nonnull
  private PostOrdersRequestPayment payment;

  public static final String SERIALIZED_NAME_SPLIT_AMOUNT_TOTAL = "splitAmountTotal";
  @SerializedName(SERIALIZED_NAME_SPLIT_AMOUNT_TOTAL)
  @javax.annotation.Nullable
  private BigDecimal splitAmountTotal;

  public static final String SERIALIZED_NAME_SESSION = "session";
  @SerializedName(SERIALIZED_NAME_SESSION)
  @javax.annotation.Nullable
  private PostOrdersRequestSession session;

  public static final String SERIALIZED_NAME_SHIPPING_FEE = "shippingFee";
  @SerializedName(SERIALIZED_NAME_SHIPPING_FEE)
  @javax.annotation.Nonnull
  private BigDecimal shippingFee = new BigDecimal("0");

  public static final String SERIALIZED_NAME_TAX_FEE = "taxFee";
  @SerializedName(SERIALIZED_NAME_TAX_FEE)
  @javax.annotation.Nonnull
  private BigDecimal taxFee = new BigDecimal("0");

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  @javax.annotation.Nullable
  private Object metadata;

  public PostOrdersRequest() {
  }

  public PostOrdersRequest chargeAmount(@javax.annotation.Nonnull BigDecimal chargeAmount) {
    this.chargeAmount = chargeAmount;
    return this;
  }

  /**
   * Total amount to be charged on the order in floating point value
   * @return chargeAmount
   */
  @javax.annotation.Nonnull
  public BigDecimal getChargeAmount() {
    return chargeAmount;
  }

  public void setChargeAmount(@javax.annotation.Nonnull BigDecimal chargeAmount) {
    this.chargeAmount = chargeAmount;
  }


  public PostOrdersRequest clientIp(@javax.annotation.Nonnull String clientIp) {
    this.clientIp = clientIp;
    return this;
  }

  /**
   * Client IP address
   * @return clientIp
   */
  @javax.annotation.Nonnull
  public String getClientIp() {
    return clientIp;
  }

  public void setClientIp(@javax.annotation.Nonnull String clientIp) {
    this.clientIp = clientIp;
  }


  public PostOrdersRequest customer(@javax.annotation.Nonnull Customer customer) {
    this.customer = customer;
    return this;
  }

  /**
   * Get customer
   * @return customer
   */
  @javax.annotation.Nonnull
  public Customer getCustomer() {
    return customer;
  }

  public void setCustomer(@javax.annotation.Nonnull Customer customer) {
    this.customer = customer;
  }


  public PostOrdersRequest discountAmount(@javax.annotation.Nonnull BigDecimal discountAmount) {
    this.discountAmount = discountAmount;
    return this;
  }

  /**
   * Discount amount
   * @return discountAmount
   */
  @javax.annotation.Nonnull
  public BigDecimal getDiscountAmount() {
    return discountAmount;
  }

  public void setDiscountAmount(@javax.annotation.Nonnull BigDecimal discountAmount) {
    this.discountAmount = discountAmount;
  }


  public PostOrdersRequest externalId(@javax.annotation.Nonnull String externalId) {
    this.externalId = externalId;
    return this;
  }

  /**
   * Order ID in your system
   * @return externalId
   */
  @javax.annotation.Nonnull
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(@javax.annotation.Nonnull String externalId) {
    this.externalId = externalId;
  }


  public PostOrdersRequest fingerprints(@javax.annotation.Nullable PostOrdersRequestFingerprints fingerprints) {
    this.fingerprints = fingerprints;
    return this;
  }

  /**
   * Get fingerprints
   * @return fingerprints
   */
  @javax.annotation.Nullable
  public PostOrdersRequestFingerprints getFingerprints() {
    return fingerprints;
  }

  public void setFingerprints(@javax.annotation.Nullable PostOrdersRequestFingerprints fingerprints) {
    this.fingerprints = fingerprints;
  }


  public PostOrdersRequest items(@javax.annotation.Nullable List<PostOrdersRequestItemsInner> items) {
    this.items = items;
    return this;
  }

  public PostOrdersRequest addItemsItem(PostOrdersRequestItemsInner itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * List of products or services in the order
   * @return items
   */
  @javax.annotation.Nullable
  public List<PostOrdersRequestItemsInner> getItems() {
    return items;
  }

  public void setItems(@javax.annotation.Nullable List<PostOrdersRequestItemsInner> items) {
    this.items = items;
  }


  public PostOrdersRequest merchant(@javax.annotation.Nullable MerchantInput merchant) {
    this.merchant = merchant;
    return this;
  }

  /**
   * Get merchant
   * @return merchant
   */
  @javax.annotation.Nullable
  public MerchantInput getMerchant() {
    return merchant;
  }

  public void setMerchant(@javax.annotation.Nullable MerchantInput merchant) {
    this.merchant = merchant;
  }


  public PostOrdersRequest payment(@javax.annotation.Nonnull PostOrdersRequestPayment payment) {
    this.payment = payment;
    return this;
  }

  /**
   * Get payment
   * @return payment
   */
  @javax.annotation.Nonnull
  public PostOrdersRequestPayment getPayment() {
    return payment;
  }

  public void setPayment(@javax.annotation.Nonnull PostOrdersRequestPayment payment) {
    this.payment = payment;
  }


  public PostOrdersRequest splitAmountTotal(@javax.annotation.Nullable BigDecimal splitAmountTotal) {
    this.splitAmountTotal = splitAmountTotal;
    return this;
  }

  /**
   * Total split amount to be paid to the merchant (Used only for reporting purposes, does not generate actual split)
   * minimum: 0
   * @return splitAmountTotal
   */
  @javax.annotation.Nullable
  public BigDecimal getSplitAmountTotal() {
    return splitAmountTotal;
  }

  public void setSplitAmountTotal(@javax.annotation.Nullable BigDecimal splitAmountTotal) {
    this.splitAmountTotal = splitAmountTotal;
  }


  public PostOrdersRequest session(@javax.annotation.Nullable PostOrdersRequestSession session) {
    this.session = session;
    return this;
  }

  /**
   * Get session
   * @return session
   */
  @javax.annotation.Nullable
  public PostOrdersRequestSession getSession() {
    return session;
  }

  public void setSession(@javax.annotation.Nullable PostOrdersRequestSession session) {
    this.session = session;
  }


  public PostOrdersRequest shippingFee(@javax.annotation.Nonnull BigDecimal shippingFee) {
    this.shippingFee = shippingFee;
    return this;
  }

  /**
   * Shipping fee
   * @return shippingFee
   */
  @javax.annotation.Nonnull
  public BigDecimal getShippingFee() {
    return shippingFee;
  }

  public void setShippingFee(@javax.annotation.Nonnull BigDecimal shippingFee) {
    this.shippingFee = shippingFee;
  }


  public PostOrdersRequest taxFee(@javax.annotation.Nonnull BigDecimal taxFee) {
    this.taxFee = taxFee;
    return this;
  }

  /**
   * Additional fees
   * @return taxFee
   */
  @javax.annotation.Nonnull
  public BigDecimal getTaxFee() {
    return taxFee;
  }

  public void setTaxFee(@javax.annotation.Nonnull BigDecimal taxFee) {
    this.taxFee = taxFee;
  }


  public PostOrdersRequest metadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Additional metadata for the order as key-value pairs. Keys should not contain spaces or special characters
   * @return metadata
   */
  @javax.annotation.Nullable
  public Object getMetadata() {
    return metadata;
  }

  public void setMetadata(@javax.annotation.Nullable Object metadata) {
    this.metadata = metadata;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostOrdersRequest postOrdersRequest = (PostOrdersRequest) o;
    return Objects.equals(this.chargeAmount, postOrdersRequest.chargeAmount) &&
        Objects.equals(this.clientIp, postOrdersRequest.clientIp) &&
        Objects.equals(this.customer, postOrdersRequest.customer) &&
        Objects.equals(this.discountAmount, postOrdersRequest.discountAmount) &&
        Objects.equals(this.externalId, postOrdersRequest.externalId) &&
        Objects.equals(this.fingerprints, postOrdersRequest.fingerprints) &&
        Objects.equals(this.items, postOrdersRequest.items) &&
        Objects.equals(this.merchant, postOrdersRequest.merchant) &&
        Objects.equals(this.payment, postOrdersRequest.payment) &&
        Objects.equals(this.splitAmountTotal, postOrdersRequest.splitAmountTotal) &&
        Objects.equals(this.session, postOrdersRequest.session) &&
        Objects.equals(this.shippingFee, postOrdersRequest.shippingFee) &&
        Objects.equals(this.taxFee, postOrdersRequest.taxFee) &&
        Objects.equals(this.metadata, postOrdersRequest.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chargeAmount, clientIp, customer, discountAmount, externalId, fingerprints, items, merchant, payment, splitAmountTotal, session, shippingFee, taxFee, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostOrdersRequest {\n");
    sb.append("    chargeAmount: ").append(toIndentedString(chargeAmount)).append("\n");
    sb.append("    clientIp: ").append(toIndentedString(clientIp)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    fingerprints: ").append(toIndentedString(fingerprints)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    merchant: ").append(toIndentedString(merchant)).append("\n");
    sb.append("    payment: ").append(toIndentedString(payment)).append("\n");
    sb.append("    splitAmountTotal: ").append(toIndentedString(splitAmountTotal)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    shippingFee: ").append(toIndentedString(shippingFee)).append("\n");
    sb.append("    taxFee: ").append(toIndentedString(taxFee)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("chargeAmount", "clientIp", "customer", "discountAmount", "externalId", "fingerprints", "items", "merchant", "payment", "splitAmountTotal", "session", "shippingFee", "taxFee", "metadata"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("chargeAmount", "clientIp", "customer", "discountAmount", "externalId", "payment", "shippingFee", "taxFee"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PostOrdersRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostOrdersRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PostOrdersRequest is not found in the empty JSON string", PostOrdersRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostOrdersRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PostOrdersRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostOrdersRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("clientIp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `clientIp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("clientIp").toString()));
      }
      // validate the required field `customer`
      Customer.validateJsonElement(jsonObj.get("customer"));
      if (!jsonObj.get("externalId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `externalId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalId").toString()));
      }
      // validate the optional field `fingerprints`
      if (jsonObj.get("fingerprints") != null && !jsonObj.get("fingerprints").isJsonNull()) {
        PostOrdersRequestFingerprints.validateJsonElement(jsonObj.get("fingerprints"));
      }
      if (jsonObj.get("items") != null && !jsonObj.get("items").isJsonNull()) {
        JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
        if (jsonArrayitems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("items").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `items` to be an array in the JSON string but got `%s`", jsonObj.get("items").toString()));
          }

          // validate the optional field `items` (array)
          for (int i = 0; i < jsonArrayitems.size(); i++) {
            PostOrdersRequestItemsInner.validateJsonElement(jsonArrayitems.get(i));
          };
        }
      }
      // validate the optional field `merchant`
      if (jsonObj.get("merchant") != null && !jsonObj.get("merchant").isJsonNull()) {
        MerchantInput.validateJsonElement(jsonObj.get("merchant"));
      }
      // validate the required field `payment`
      PostOrdersRequestPayment.validateJsonElement(jsonObj.get("payment"));
      // validate the optional field `session`
      if (jsonObj.get("session") != null && !jsonObj.get("session").isJsonNull()) {
        PostOrdersRequestSession.validateJsonElement(jsonObj.get("session"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostOrdersRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostOrdersRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostOrdersRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostOrdersRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<PostOrdersRequest>() {
           @Override
           public void write(JsonWriter out, PostOrdersRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostOrdersRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PostOrdersRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostOrdersRequest
   * @throws IOException if the JSON string is invalid with respect to PostOrdersRequest
   */
  public static PostOrdersRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostOrdersRequest.class);
  }

  /**
   * Convert an instance of PostOrdersRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

