/*
 * PayConductor API
 * PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PostOrders200ResponseBankSlip;
import org.openapitools.client.model.PostOrders200ResponseCreditCard;
import org.openapitools.client.model.PostOrders200ResponseNuPay;
import org.openapitools.client.model.PostOrders200ResponseOrderItemsInner;
import org.openapitools.client.model.PostOrders200ResponsePicPay;
import org.openapitools.client.model.PostOrders200ResponsePix;
import org.openapitools.client.model.PostOrders200ResponseSession;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * PostOrders200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-18T15:58:14.340077800-03:00[America/Bahia]", comments = "Generator version: 7.20.0")
public class PostOrders200Response {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_EXTERNAL_ID = "externalId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_ID)
  @javax.annotation.Nullable
  private String externalId;

  public static final String SERIALIZED_NAME_EXTERNAL_INTEGRATION_KEY = "externalIntegrationKey";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_INTEGRATION_KEY)
  @javax.annotation.Nonnull
  private String externalIntegrationKey;

  public static final String SERIALIZED_NAME_EXTERNAL_INTEGRATION_ID = "externalIntegrationId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_INTEGRATION_ID)
  @javax.annotation.Nullable
  private String externalIntegrationId;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  @javax.annotation.Nonnull
  private BigDecimal amount;

  public static final String SERIALIZED_NAME_COST_FEE = "costFee";
  @SerializedName(SERIALIZED_NAME_COST_FEE)
  @javax.annotation.Nonnull
  private BigDecimal costFee;

  public static final String SERIALIZED_NAME_PIX = "pix";
  @SerializedName(SERIALIZED_NAME_PIX)
  @javax.annotation.Nullable
  private PostOrders200ResponsePix pix;

  public static final String SERIALIZED_NAME_BANK_SLIP = "bankSlip";
  @SerializedName(SERIALIZED_NAME_BANK_SLIP)
  @javax.annotation.Nullable
  private PostOrders200ResponseBankSlip bankSlip;

  public static final String SERIALIZED_NAME_NU_PAY = "nuPay";
  @SerializedName(SERIALIZED_NAME_NU_PAY)
  @javax.annotation.Nullable
  private PostOrders200ResponseNuPay nuPay;

  public static final String SERIALIZED_NAME_PIC_PAY = "picPay";
  @SerializedName(SERIALIZED_NAME_PIC_PAY)
  @javax.annotation.Nullable
  private PostOrders200ResponsePicPay picPay;

  public static final String SERIALIZED_NAME_CREDIT_CARD = "creditCard";
  @SerializedName(SERIALIZED_NAME_CREDIT_CARD)
  @javax.annotation.Nullable
  private PostOrders200ResponseCreditCard creditCard;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    GENERATING("Generating"),
    
    PENDING("Pending"),
    
    COMPLETED("Completed"),
    
    FAILED("Failed"),
    
    CANCELED("Canceled"),
    
    REFUNDING("Refunding"),
    
    REFUNDED("Refunded"),
    
    IN_DISPUTE("InDispute"),
    
    CHARGEBACK("Chargeback");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatusEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      StatusEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private StatusEnum status;

  /**
   * Gets or Sets paymentMethod
   */
  @JsonAdapter(PaymentMethodEnum.Adapter.class)
  public enum PaymentMethodEnum {
    PIX("Pix"),
    
    CREDIT_CARD("CreditCard"),
    
    DEBIT_CARD("DebitCard"),
    
    BANK_SLIP("BankSlip"),
    
    CRYPTO("Crypto"),
    
    APPLE_PAY("ApplePay"),
    
    NU_PAY("NuPay"),
    
    PIC_PAY("PicPay"),
    
    AMAZON_PAY("AmazonPay"),
    
    SEPA_DEBIT("SepaDebit"),
    
    GOOGLE_PAY("GooglePay");

    private String value;

    PaymentMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PaymentMethodEnum fromValue(String value) {
      for (PaymentMethodEnum b : PaymentMethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PaymentMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PaymentMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PaymentMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PaymentMethodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PaymentMethodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PAYMENT_METHOD = "paymentMethod";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHOD)
  @javax.annotation.Nonnull
  private PaymentMethodEnum paymentMethod;

  public static final String SERIALIZED_NAME_PAYED_AT = "payedAt";
  @SerializedName(SERIALIZED_NAME_PAYED_AT)
  @javax.annotation.Nullable
  private String payedAt;

  public static final String SERIALIZED_NAME_ERROR_CODE = "errorCode";
  @SerializedName(SERIALIZED_NAME_ERROR_CODE)
  @javax.annotation.Nullable
  private String errorCode;

  public static final String SERIALIZED_NAME_ERROR_MESSAGE = "errorMessage";
  @SerializedName(SERIALIZED_NAME_ERROR_MESSAGE)
  @javax.annotation.Nullable
  private String errorMessage;

  public static final String SERIALIZED_NAME_ORDER_ITEMS = "orderItems";
  @SerializedName(SERIALIZED_NAME_ORDER_ITEMS)
  @javax.annotation.Nonnull
  private List<PostOrders200ResponseOrderItemsInner> orderItems = new ArrayList<>();

  public static final String SERIALIZED_NAME_SESSION = "session";
  @SerializedName(SERIALIZED_NAME_SESSION)
  @javax.annotation.Nullable
  private PostOrders200ResponseSession session;

  public PostOrders200Response() {
  }

  public PostOrders200Response id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Order ID in the system
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public PostOrders200Response externalId(@javax.annotation.Nullable String externalId) {
    this.externalId = externalId;
    return this;
  }

  /**
   * External order ID (provided by your integration)
   * @return externalId
   */
  @javax.annotation.Nullable
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(@javax.annotation.Nullable String externalId) {
    this.externalId = externalId;
  }


  public PostOrders200Response externalIntegrationKey(@javax.annotation.Nonnull String externalIntegrationKey) {
    this.externalIntegrationKey = externalIntegrationKey;
    return this;
  }

  /**
   * Provider used to process the order
   * @return externalIntegrationKey
   */
  @javax.annotation.Nonnull
  public String getExternalIntegrationKey() {
    return externalIntegrationKey;
  }

  public void setExternalIntegrationKey(@javax.annotation.Nonnull String externalIntegrationKey) {
    this.externalIntegrationKey = externalIntegrationKey;
  }


  public PostOrders200Response externalIntegrationId(@javax.annotation.Nullable String externalIntegrationId) {
    this.externalIntegrationId = externalIntegrationId;
    return this;
  }

  /**
   * Order ID in the payment provider
   * @return externalIntegrationId
   */
  @javax.annotation.Nullable
  public String getExternalIntegrationId() {
    return externalIntegrationId;
  }

  public void setExternalIntegrationId(@javax.annotation.Nullable String externalIntegrationId) {
    this.externalIntegrationId = externalIntegrationId;
  }


  public PostOrders200Response amount(@javax.annotation.Nonnull BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Total order amount
   * @return amount
   */
  @javax.annotation.Nonnull
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(@javax.annotation.Nonnull BigDecimal amount) {
    this.amount = amount;
  }


  public PostOrders200Response costFee(@javax.annotation.Nonnull BigDecimal costFee) {
    this.costFee = costFee;
    return this;
  }

  /**
   * Cost fee applied to the order
   * @return costFee
   */
  @javax.annotation.Nonnull
  public BigDecimal getCostFee() {
    return costFee;
  }

  public void setCostFee(@javax.annotation.Nonnull BigDecimal costFee) {
    this.costFee = costFee;
  }


  public PostOrders200Response pix(@javax.annotation.Nullable PostOrders200ResponsePix pix) {
    this.pix = pix;
    return this;
  }

  /**
   * Get pix
   * @return pix
   */
  @javax.annotation.Nullable
  public PostOrders200ResponsePix getPix() {
    return pix;
  }

  public void setPix(@javax.annotation.Nullable PostOrders200ResponsePix pix) {
    this.pix = pix;
  }


  public PostOrders200Response bankSlip(@javax.annotation.Nullable PostOrders200ResponseBankSlip bankSlip) {
    this.bankSlip = bankSlip;
    return this;
  }

  /**
   * Get bankSlip
   * @return bankSlip
   */
  @javax.annotation.Nullable
  public PostOrders200ResponseBankSlip getBankSlip() {
    return bankSlip;
  }

  public void setBankSlip(@javax.annotation.Nullable PostOrders200ResponseBankSlip bankSlip) {
    this.bankSlip = bankSlip;
  }


  public PostOrders200Response nuPay(@javax.annotation.Nullable PostOrders200ResponseNuPay nuPay) {
    this.nuPay = nuPay;
    return this;
  }

  /**
   * Get nuPay
   * @return nuPay
   */
  @javax.annotation.Nullable
  public PostOrders200ResponseNuPay getNuPay() {
    return nuPay;
  }

  public void setNuPay(@javax.annotation.Nullable PostOrders200ResponseNuPay nuPay) {
    this.nuPay = nuPay;
  }


  public PostOrders200Response picPay(@javax.annotation.Nullable PostOrders200ResponsePicPay picPay) {
    this.picPay = picPay;
    return this;
  }

  /**
   * Get picPay
   * @return picPay
   */
  @javax.annotation.Nullable
  public PostOrders200ResponsePicPay getPicPay() {
    return picPay;
  }

  public void setPicPay(@javax.annotation.Nullable PostOrders200ResponsePicPay picPay) {
    this.picPay = picPay;
  }


  public PostOrders200Response creditCard(@javax.annotation.Nullable PostOrders200ResponseCreditCard creditCard) {
    this.creditCard = creditCard;
    return this;
  }

  /**
   * Get creditCard
   * @return creditCard
   */
  @javax.annotation.Nullable
  public PostOrders200ResponseCreditCard getCreditCard() {
    return creditCard;
  }

  public void setCreditCard(@javax.annotation.Nullable PostOrders200ResponseCreditCard creditCard) {
    this.creditCard = creditCard;
  }


  public PostOrders200Response status(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public PostOrders200Response paymentMethod(@javax.annotation.Nonnull PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

  /**
   * Get paymentMethod
   * @return paymentMethod
   */
  @javax.annotation.Nonnull
  public PaymentMethodEnum getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(@javax.annotation.Nonnull PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
  }


  public PostOrders200Response payedAt(@javax.annotation.Nullable String payedAt) {
    this.payedAt = payedAt;
    return this;
  }

  /**
   * Date and time when the order was paid (ISO 8601)
   * @return payedAt
   */
  @javax.annotation.Nullable
  public String getPayedAt() {
    return payedAt;
  }

  public void setPayedAt(@javax.annotation.Nullable String payedAt) {
    this.payedAt = payedAt;
  }


  public PostOrders200Response errorCode(@javax.annotation.Nullable String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

  /**
   * Error code, if any
   * @return errorCode
   */
  @javax.annotation.Nullable
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(@javax.annotation.Nullable String errorCode) {
    this.errorCode = errorCode;
  }


  public PostOrders200Response errorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * Error message, if any
   * @return errorMessage
   */
  @javax.annotation.Nullable
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
  }


  public PostOrders200Response orderItems(@javax.annotation.Nonnull List<PostOrders200ResponseOrderItemsInner> orderItems) {
    this.orderItems = orderItems;
    return this;
  }

  public PostOrders200Response addOrderItemsItem(PostOrders200ResponseOrderItemsInner orderItemsItem) {
    if (this.orderItems == null) {
      this.orderItems = new ArrayList<>();
    }
    this.orderItems.add(orderItemsItem);
    return this;
  }

  /**
   * Get orderItems
   * @return orderItems
   */
  @javax.annotation.Nonnull
  public List<PostOrders200ResponseOrderItemsInner> getOrderItems() {
    return orderItems;
  }

  public void setOrderItems(@javax.annotation.Nonnull List<PostOrders200ResponseOrderItemsInner> orderItems) {
    this.orderItems = orderItems;
  }


  public PostOrders200Response session(@javax.annotation.Nullable PostOrders200ResponseSession session) {
    this.session = session;
    return this;
  }

  /**
   * Get session
   * @return session
   */
  @javax.annotation.Nullable
  public PostOrders200ResponseSession getSession() {
    return session;
  }

  public void setSession(@javax.annotation.Nullable PostOrders200ResponseSession session) {
    this.session = session;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostOrders200Response postOrders200Response = (PostOrders200Response) o;
    return Objects.equals(this.id, postOrders200Response.id) &&
        Objects.equals(this.externalId, postOrders200Response.externalId) &&
        Objects.equals(this.externalIntegrationKey, postOrders200Response.externalIntegrationKey) &&
        Objects.equals(this.externalIntegrationId, postOrders200Response.externalIntegrationId) &&
        Objects.equals(this.amount, postOrders200Response.amount) &&
        Objects.equals(this.costFee, postOrders200Response.costFee) &&
        Objects.equals(this.pix, postOrders200Response.pix) &&
        Objects.equals(this.bankSlip, postOrders200Response.bankSlip) &&
        Objects.equals(this.nuPay, postOrders200Response.nuPay) &&
        Objects.equals(this.picPay, postOrders200Response.picPay) &&
        Objects.equals(this.creditCard, postOrders200Response.creditCard) &&
        Objects.equals(this.status, postOrders200Response.status) &&
        Objects.equals(this.paymentMethod, postOrders200Response.paymentMethod) &&
        Objects.equals(this.payedAt, postOrders200Response.payedAt) &&
        Objects.equals(this.errorCode, postOrders200Response.errorCode) &&
        Objects.equals(this.errorMessage, postOrders200Response.errorMessage) &&
        Objects.equals(this.orderItems, postOrders200Response.orderItems) &&
        Objects.equals(this.session, postOrders200Response.session);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, externalId, externalIntegrationKey, externalIntegrationId, amount, costFee, pix, bankSlip, nuPay, picPay, creditCard, status, paymentMethod, payedAt, errorCode, errorMessage, orderItems, session);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostOrders200Response {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    externalIntegrationKey: ").append(toIndentedString(externalIntegrationKey)).append("\n");
    sb.append("    externalIntegrationId: ").append(toIndentedString(externalIntegrationId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    costFee: ").append(toIndentedString(costFee)).append("\n");
    sb.append("    pix: ").append(toIndentedString(pix)).append("\n");
    sb.append("    bankSlip: ").append(toIndentedString(bankSlip)).append("\n");
    sb.append("    nuPay: ").append(toIndentedString(nuPay)).append("\n");
    sb.append("    picPay: ").append(toIndentedString(picPay)).append("\n");
    sb.append("    creditCard: ").append(toIndentedString(creditCard)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    payedAt: ").append(toIndentedString(payedAt)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    orderItems: ").append(toIndentedString(orderItems)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "externalId", "externalIntegrationKey", "externalIntegrationId", "amount", "costFee", "pix", "bankSlip", "nuPay", "picPay", "creditCard", "status", "paymentMethod", "payedAt", "errorCode", "errorMessage", "orderItems", "session"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "externalId", "externalIntegrationKey", "externalIntegrationId", "amount", "costFee", "status", "paymentMethod", "payedAt", "errorCode", "errorMessage", "orderItems"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PostOrders200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostOrders200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PostOrders200Response is not found in the empty JSON string", PostOrders200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostOrders200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PostOrders200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PostOrders200Response.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("externalId") != null && !jsonObj.get("externalId").isJsonNull()) && !jsonObj.get("externalId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `externalId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalId").toString()));
      }
      if (!jsonObj.get("externalIntegrationKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `externalIntegrationKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalIntegrationKey").toString()));
      }
      if ((jsonObj.get("externalIntegrationId") != null && !jsonObj.get("externalIntegrationId").isJsonNull()) && !jsonObj.get("externalIntegrationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `externalIntegrationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalIntegrationId").toString()));
      }
      // validate the optional field `pix`
      if (jsonObj.get("pix") != null && !jsonObj.get("pix").isJsonNull()) {
        PostOrders200ResponsePix.validateJsonElement(jsonObj.get("pix"));
      }
      // validate the optional field `bankSlip`
      if (jsonObj.get("bankSlip") != null && !jsonObj.get("bankSlip").isJsonNull()) {
        PostOrders200ResponseBankSlip.validateJsonElement(jsonObj.get("bankSlip"));
      }
      // validate the optional field `nuPay`
      if (jsonObj.get("nuPay") != null && !jsonObj.get("nuPay").isJsonNull()) {
        PostOrders200ResponseNuPay.validateJsonElement(jsonObj.get("nuPay"));
      }
      // validate the optional field `picPay`
      if (jsonObj.get("picPay") != null && !jsonObj.get("picPay").isJsonNull()) {
        PostOrders200ResponsePicPay.validateJsonElement(jsonObj.get("picPay"));
      }
      // validate the optional field `creditCard`
      if (jsonObj.get("creditCard") != null && !jsonObj.get("creditCard").isJsonNull()) {
        PostOrders200ResponseCreditCard.validateJsonElement(jsonObj.get("creditCard"));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the required field `status`
      StatusEnum.validateJsonElement(jsonObj.get("status"));
      if (!jsonObj.get("paymentMethod").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `paymentMethod` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paymentMethod").toString()));
      }
      // validate the required field `paymentMethod`
      PaymentMethodEnum.validateJsonElement(jsonObj.get("paymentMethod"));
      if ((jsonObj.get("payedAt") != null && !jsonObj.get("payedAt").isJsonNull()) && !jsonObj.get("payedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payedAt").toString()));
      }
      if ((jsonObj.get("errorCode") != null && !jsonObj.get("errorCode").isJsonNull()) && !jsonObj.get("errorCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `errorCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("errorCode").toString()));
      }
      if ((jsonObj.get("errorMessage") != null && !jsonObj.get("errorMessage").isJsonNull()) && !jsonObj.get("errorMessage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `errorMessage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("errorMessage").toString()));
      }
      if (jsonObj.get("orderItems") != null) {
        if (!jsonObj.get("orderItems").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `orderItems` to be an array in the JSON string but got `%s`", jsonObj.get("orderItems").toString()));
        }
        JsonArray jsonArrayorderItems = jsonObj.getAsJsonArray("orderItems");
        // validate the required field `orderItems` (array)
        for (int i = 0; i < jsonArrayorderItems.size(); i++) {
          PostOrders200ResponseOrderItemsInner.validateJsonElement(jsonArrayorderItems.get(i));
        }
      }
      // validate the optional field `session`
      if (jsonObj.get("session") != null && !jsonObj.get("session").isJsonNull()) {
        PostOrders200ResponseSession.validateJsonElement(jsonObj.get("session"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostOrders200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostOrders200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostOrders200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostOrders200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<PostOrders200Response>() {
           @Override
           public void write(JsonWriter out, PostOrders200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostOrders200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PostOrders200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostOrders200Response
   * @throws IOException if the JSON string is invalid with respect to PostOrders200Response
   */
  public static PostOrders200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostOrders200Response.class);
  }

  /**
   * Convert an instance of PostOrders200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

