/*
 * PayConductor API
 * # Introdução  Esta documentação cobre todas as funcionalidades disponíveis na API RESTful do PayConductor, incluindo autenticação, gerenciamento de recursos e exemplos de uso.  <br />  <br />  ----  <br />   # Autenticação  A API do PayConductor utiliza autenticação HTTP Basic para validar requisições. Você precisa fornecer suas credenciais (Client ID e Client Secret) no formato `client:secret` codificado em Base64.  <br />  ## Obtendo Credenciais  1. Acesse o painel administrativo do PayConductor 2. Navegue até **Configurações > API Keys** 3. Gere um novo par de credenciais (Client ID e Client Secret) 4. Guarde o Client Secret em local seguro - ele não será exibido novamente  <br />  ## Formato de Autenticação  As credenciais devem ser enviadas no header `Authorization` usando o esquema Basic:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Exemplo em Node.js  ```javascript const clientId = 'seu_client_id'; const clientSecret = 'seu_client_secret';  // Codifica as credenciais em Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Erros de Autenticação  | Código | Descrição | |--------|-----------| | `401`  | Credenciais inválidas ou ausentes | | `403`  | Credenciais válidas, mas sem permissão para o recurso | | `429`  | Muitas requisições (rate limit excedido) |  ### Exemplo de resposta de erro  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Caso o externalSessionId ou sessionId sejam fornecidos e houver uma sessão existente, ela será atualizada com os novos dados. Caso contrário, uma nova sessão será criada.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-18T14:44:19.268927700-03:00[America/Bahia]", comments = "Generator version: 7.20.0")
public class PostOrdersRequestSession {
  public static final String SERIALIZED_NAME_EXPIRES_IN_MINUTES = "expiresInMinutes";
  @SerializedName(SERIALIZED_NAME_EXPIRES_IN_MINUTES)
  @javax.annotation.Nullable
  private BigDecimal expiresInMinutes = new BigDecimal("30");

  public static final String SERIALIZED_NAME_CHECKOUT_URL = "checkoutUrl";
  @SerializedName(SERIALIZED_NAME_CHECKOUT_URL)
  @javax.annotation.Nullable
  private String checkoutUrl;

  public static final String SERIALIZED_NAME_SESSION_ID = "sessionId";
  @SerializedName(SERIALIZED_NAME_SESSION_ID)
  @javax.annotation.Nullable
  private String sessionId;

  public static final String SERIALIZED_NAME_EXTERNAL_SESSION_ID = "externalSessionId";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_SESSION_ID)
  @javax.annotation.Nullable
  private String externalSessionId;

  public PostOrdersRequestSession() {
  }

  public PostOrdersRequestSession expiresInMinutes(@javax.annotation.Nullable BigDecimal expiresInMinutes) {
    this.expiresInMinutes = expiresInMinutes;
    return this;
  }

  /**
   * Tempo em minutos para expiração da sessão do checkout
   * minimum: 15
   * @return expiresInMinutes
   */
  @javax.annotation.Nullable
  public BigDecimal getExpiresInMinutes() {
    return expiresInMinutes;
  }

  public void setExpiresInMinutes(@javax.annotation.Nullable BigDecimal expiresInMinutes) {
    this.expiresInMinutes = expiresInMinutes;
  }


  public PostOrdersRequestSession checkoutUrl(@javax.annotation.Nullable String checkoutUrl) {
    this.checkoutUrl = checkoutUrl;
    return this;
  }

  /**
   * URL do checkout para que possamos redirecionar
   * @return checkoutUrl
   */
  @javax.annotation.Nullable
  public String getCheckoutUrl() {
    return checkoutUrl;
  }

  public void setCheckoutUrl(@javax.annotation.Nullable String checkoutUrl) {
    this.checkoutUrl = checkoutUrl;
  }


  public PostOrdersRequestSession sessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

  /**
   * Id gerado pelo nosso serviço para identificar a sessão de checkout
   * @return sessionId
   */
  @javax.annotation.Nullable
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
  }


  public PostOrdersRequestSession externalSessionId(@javax.annotation.Nullable String externalSessionId) {
    this.externalSessionId = externalSessionId;
    return this;
  }

  /**
   * Id da sessão de checkout gerado pelo lado do cliente. O id deve ser único para cada sessão de carrinho
   * @return externalSessionId
   */
  @javax.annotation.Nullable
  public String getExternalSessionId() {
    return externalSessionId;
  }

  public void setExternalSessionId(@javax.annotation.Nullable String externalSessionId) {
    this.externalSessionId = externalSessionId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostOrdersRequestSession postOrdersRequestSession = (PostOrdersRequestSession) o;
    return Objects.equals(this.expiresInMinutes, postOrdersRequestSession.expiresInMinutes) &&
        Objects.equals(this.checkoutUrl, postOrdersRequestSession.checkoutUrl) &&
        Objects.equals(this.sessionId, postOrdersRequestSession.sessionId) &&
        Objects.equals(this.externalSessionId, postOrdersRequestSession.externalSessionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiresInMinutes, checkoutUrl, sessionId, externalSessionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostOrdersRequestSession {\n");
    sb.append("    expiresInMinutes: ").append(toIndentedString(expiresInMinutes)).append("\n");
    sb.append("    checkoutUrl: ").append(toIndentedString(checkoutUrl)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    externalSessionId: ").append(toIndentedString(externalSessionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("expiresInMinutes", "checkoutUrl", "sessionId", "externalSessionId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PostOrdersRequestSession
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PostOrdersRequestSession.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PostOrdersRequestSession is not found in the empty JSON string", PostOrdersRequestSession.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PostOrdersRequestSession.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PostOrdersRequestSession` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("checkoutUrl") != null && !jsonObj.get("checkoutUrl").isJsonNull()) && !jsonObj.get("checkoutUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `checkoutUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("checkoutUrl").toString()));
      }
      if ((jsonObj.get("sessionId") != null && !jsonObj.get("sessionId").isJsonNull()) && !jsonObj.get("sessionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sessionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sessionId").toString()));
      }
      if ((jsonObj.get("externalSessionId") != null && !jsonObj.get("externalSessionId").isJsonNull()) && !jsonObj.get("externalSessionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `externalSessionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("externalSessionId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PostOrdersRequestSession.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PostOrdersRequestSession' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PostOrdersRequestSession> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PostOrdersRequestSession.class));

       return (TypeAdapter<T>) new TypeAdapter<PostOrdersRequestSession>() {
           @Override
           public void write(JsonWriter out, PostOrdersRequestSession value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PostOrdersRequestSession read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PostOrdersRequestSession given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PostOrdersRequestSession
   * @throws IOException if the JSON string is invalid with respect to PostOrdersRequestSession
   */
  public static PostOrdersRequestSession fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PostOrdersRequestSession.class);
  }

  /**
   * Convert an instance of PostOrdersRequestSession to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

