=begin
#PayConductor API

#PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module OpenapiClient
  class CompleteCardData < ApiModelBase
    # Card security code (CVV)
    attr_accessor :cvv

    attr_accessor :expiration

    # Card holder name
    attr_accessor :holder_name

    # Credit card number
    attr_accessor :number

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'cvv' => :'cvv',
        :'expiration' => :'expiration',
        :'holder_name' => :'holderName',
        :'number' => :'number'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'cvv' => :'String',
        :'expiration' => :'CompleteCardDataExpiration',
        :'holder_name' => :'String',
        :'number' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::CompleteCardData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::CompleteCardData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'cvv')
        self.cvv = attributes[:'cvv']
      else
        self.cvv = nil
      end

      if attributes.key?(:'expiration')
        self.expiration = attributes[:'expiration']
      else
        self.expiration = nil
      end

      if attributes.key?(:'holder_name')
        self.holder_name = attributes[:'holder_name']
      else
        self.holder_name = nil
      end

      if attributes.key?(:'number')
        self.number = attributes[:'number']
      else
        self.number = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @cvv.nil?
        invalid_properties.push('invalid value for "cvv", cvv cannot be nil.')
      end

      if @cvv.to_s.length > 4
        invalid_properties.push('invalid value for "cvv", the character length must be smaller than or equal to 4.')
      end

      if @cvv.to_s.length < 3
        invalid_properties.push('invalid value for "cvv", the character length must be greater than or equal to 3.')
      end

      if @expiration.nil?
        invalid_properties.push('invalid value for "expiration", expiration cannot be nil.')
      end

      if @holder_name.nil?
        invalid_properties.push('invalid value for "holder_name", holder_name cannot be nil.')
      end

      if @number.nil?
        invalid_properties.push('invalid value for "number", number cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @cvv.nil?
      return false if @cvv.to_s.length > 4
      return false if @cvv.to_s.length < 3
      return false if @expiration.nil?
      return false if @holder_name.nil?
      return false if @number.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] cvv Value to be assigned
    def cvv=(cvv)
      if cvv.nil?
        fail ArgumentError, 'cvv cannot be nil'
      end

      if cvv.to_s.length > 4
        fail ArgumentError, 'invalid value for "cvv", the character length must be smaller than or equal to 4.'
      end

      if cvv.to_s.length < 3
        fail ArgumentError, 'invalid value for "cvv", the character length must be greater than or equal to 3.'
      end

      @cvv = cvv
    end

    # Custom attribute writer method with validation
    # @param [Object] expiration Value to be assigned
    def expiration=(expiration)
      if expiration.nil?
        fail ArgumentError, 'expiration cannot be nil'
      end

      @expiration = expiration
    end

    # Custom attribute writer method with validation
    # @param [Object] holder_name Value to be assigned
    def holder_name=(holder_name)
      if holder_name.nil?
        fail ArgumentError, 'holder_name cannot be nil'
      end

      @holder_name = holder_name
    end

    # Custom attribute writer method with validation
    # @param [Object] number Value to be assigned
    def number=(number)
      if number.nil?
        fail ArgumentError, 'number cannot be nil'
      end

      @number = number
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          cvv == o.cvv &&
          expiration == o.expiration &&
          holder_name == o.holder_name &&
          number == o.number
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [cvv, expiration, holder_name, number].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
