=begin
#PayConductor API

#PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module OpenapiClient
  class PostOrdersRequest < ApiModelBase
    # Total amount to be charged on the order in floating point value
    attr_accessor :charge_amount

    # Client IP address
    attr_accessor :client_ip

    attr_accessor :customer

    # Discount amount
    attr_accessor :discount_amount

    # Order ID in your system
    attr_accessor :external_id

    attr_accessor :fingerprints

    # List of products or services in the order
    attr_accessor :items

    attr_accessor :merchant

    attr_accessor :payment

    # Total split amount to be paid to the merchant (Used only for reporting purposes, does not generate actual split)
    attr_accessor :split_amount_total

    attr_accessor :session

    # Shipping fee
    attr_accessor :shipping_fee

    # Additional fees
    attr_accessor :tax_fee

    # Additional metadata for the order as key-value pairs. Keys should not contain spaces or special characters
    attr_accessor :metadata

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'charge_amount' => :'chargeAmount',
        :'client_ip' => :'clientIp',
        :'customer' => :'customer',
        :'discount_amount' => :'discountAmount',
        :'external_id' => :'externalId',
        :'fingerprints' => :'fingerprints',
        :'items' => :'items',
        :'merchant' => :'merchant',
        :'payment' => :'payment',
        :'split_amount_total' => :'splitAmountTotal',
        :'session' => :'session',
        :'shipping_fee' => :'shippingFee',
        :'tax_fee' => :'taxFee',
        :'metadata' => :'metadata'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'charge_amount' => :'Float',
        :'client_ip' => :'String',
        :'customer' => :'Customer',
        :'discount_amount' => :'Float',
        :'external_id' => :'String',
        :'fingerprints' => :'PostOrdersRequestFingerprints',
        :'items' => :'Array<PostOrdersRequestItemsInner>',
        :'merchant' => :'MerchantInput',
        :'payment' => :'PostOrdersRequestPayment',
        :'split_amount_total' => :'Float',
        :'session' => :'PostOrdersRequestSession',
        :'shipping_fee' => :'Float',
        :'tax_fee' => :'Float',
        :'metadata' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::PostOrdersRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::PostOrdersRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'charge_amount')
        self.charge_amount = attributes[:'charge_amount']
      else
        self.charge_amount = nil
      end

      if attributes.key?(:'client_ip')
        self.client_ip = attributes[:'client_ip']
      else
        self.client_ip = nil
      end

      if attributes.key?(:'customer')
        self.customer = attributes[:'customer']
      else
        self.customer = nil
      end

      if attributes.key?(:'discount_amount')
        self.discount_amount = attributes[:'discount_amount']
      else
        self.discount_amount = 0
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      else
        self.external_id = nil
      end

      if attributes.key?(:'fingerprints')
        self.fingerprints = attributes[:'fingerprints']
      end

      if attributes.key?(:'items')
        if (value = attributes[:'items']).is_a?(Array)
          self.items = value
        end
      end

      if attributes.key?(:'merchant')
        self.merchant = attributes[:'merchant']
      end

      if attributes.key?(:'payment')
        self.payment = attributes[:'payment']
      else
        self.payment = nil
      end

      if attributes.key?(:'split_amount_total')
        self.split_amount_total = attributes[:'split_amount_total']
      end

      if attributes.key?(:'session')
        self.session = attributes[:'session']
      end

      if attributes.key?(:'shipping_fee')
        self.shipping_fee = attributes[:'shipping_fee']
      else
        self.shipping_fee = 0
      end

      if attributes.key?(:'tax_fee')
        self.tax_fee = attributes[:'tax_fee']
      else
        self.tax_fee = 0
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @charge_amount.nil?
        invalid_properties.push('invalid value for "charge_amount", charge_amount cannot be nil.')
      end

      if @client_ip.nil?
        invalid_properties.push('invalid value for "client_ip", client_ip cannot be nil.')
      end

      if @customer.nil?
        invalid_properties.push('invalid value for "customer", customer cannot be nil.')
      end

      if @discount_amount.nil?
        invalid_properties.push('invalid value for "discount_amount", discount_amount cannot be nil.')
      end

      if @external_id.nil?
        invalid_properties.push('invalid value for "external_id", external_id cannot be nil.')
      end

      if !@items.nil? && @items.length > 20
        invalid_properties.push('invalid value for "items", number of items must be less than or equal to 20.')
      end

      if @payment.nil?
        invalid_properties.push('invalid value for "payment", payment cannot be nil.')
      end

      if !@split_amount_total.nil? && @split_amount_total < 0
        invalid_properties.push('invalid value for "split_amount_total", must be greater than or equal to 0.')
      end

      if @shipping_fee.nil?
        invalid_properties.push('invalid value for "shipping_fee", shipping_fee cannot be nil.')
      end

      if @tax_fee.nil?
        invalid_properties.push('invalid value for "tax_fee", tax_fee cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @charge_amount.nil?
      return false if @client_ip.nil?
      return false if @customer.nil?
      return false if @discount_amount.nil?
      return false if @external_id.nil?
      return false if !@items.nil? && @items.length > 20
      return false if @payment.nil?
      return false if !@split_amount_total.nil? && @split_amount_total < 0
      return false if @shipping_fee.nil?
      return false if @tax_fee.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] charge_amount Value to be assigned
    def charge_amount=(charge_amount)
      if charge_amount.nil?
        fail ArgumentError, 'charge_amount cannot be nil'
      end

      @charge_amount = charge_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] client_ip Value to be assigned
    def client_ip=(client_ip)
      if client_ip.nil?
        fail ArgumentError, 'client_ip cannot be nil'
      end

      @client_ip = client_ip
    end

    # Custom attribute writer method with validation
    # @param [Object] customer Value to be assigned
    def customer=(customer)
      if customer.nil?
        fail ArgumentError, 'customer cannot be nil'
      end

      @customer = customer
    end

    # Custom attribute writer method with validation
    # @param [Object] discount_amount Value to be assigned
    def discount_amount=(discount_amount)
      if discount_amount.nil?
        fail ArgumentError, 'discount_amount cannot be nil'
      end

      @discount_amount = discount_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] external_id Value to be assigned
    def external_id=(external_id)
      if external_id.nil?
        fail ArgumentError, 'external_id cannot be nil'
      end

      @external_id = external_id
    end

    # Custom attribute writer method with validation
    # @param [Object] items Value to be assigned
    def items=(items)
      if items.nil?
        fail ArgumentError, 'items cannot be nil'
      end

      if items.length > 20
        fail ArgumentError, 'invalid value for "items", number of items must be less than or equal to 20.'
      end

      @items = items
    end

    # Custom attribute writer method with validation
    # @param [Object] payment Value to be assigned
    def payment=(payment)
      if payment.nil?
        fail ArgumentError, 'payment cannot be nil'
      end

      @payment = payment
    end

    # Custom attribute writer method with validation
    # @param [Object] split_amount_total Value to be assigned
    def split_amount_total=(split_amount_total)
      if split_amount_total.nil?
        fail ArgumentError, 'split_amount_total cannot be nil'
      end

      if split_amount_total < 0
        fail ArgumentError, 'invalid value for "split_amount_total", must be greater than or equal to 0.'
      end

      @split_amount_total = split_amount_total
    end

    # Custom attribute writer method with validation
    # @param [Object] shipping_fee Value to be assigned
    def shipping_fee=(shipping_fee)
      if shipping_fee.nil?
        fail ArgumentError, 'shipping_fee cannot be nil'
      end

      @shipping_fee = shipping_fee
    end

    # Custom attribute writer method with validation
    # @param [Object] tax_fee Value to be assigned
    def tax_fee=(tax_fee)
      if tax_fee.nil?
        fail ArgumentError, 'tax_fee cannot be nil'
      end

      @tax_fee = tax_fee
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          charge_amount == o.charge_amount &&
          client_ip == o.client_ip &&
          customer == o.customer &&
          discount_amount == o.discount_amount &&
          external_id == o.external_id &&
          fingerprints == o.fingerprints &&
          items == o.items &&
          merchant == o.merchant &&
          payment == o.payment &&
          split_amount_total == o.split_amount_total &&
          session == o.session &&
          shipping_fee == o.shipping_fee &&
          tax_fee == o.tax_fee &&
          metadata == o.metadata
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [charge_amount, client_ip, customer, discount_amount, external_id, fingerprints, items, merchant, payment, split_amount_total, session, shipping_fee, tax_fee, metadata].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
