# coding: utf-8

"""
    PayConductor API

    PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from payconductor-sdk.models.post_withdraws200_response import PostWithdraws200Response

class TestPostWithdraws200Response(unittest.TestCase):
    """PostWithdraws200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWithdraws200Response:
        """Test PostWithdraws200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWithdraws200Response`
        """
        model = PostWithdraws200Response()
        if include_optional:
            return PostWithdraws200Response(
                id = '',
                external_id = '',
                external_integration_key = '',
                external_integration_id = '',
                cost_fee = 1.337,
                status = 'Pending',
                error_code = '',
                error_message = '',
                payed_at = None,
                payout_account = payconductor-sdk.models.post_withdraws_200_response_payout_account.postWithdraws_200_response_payoutAccount(
                    id = '', 
                    owner_document = '48072888001528', 
                    owner_name = '', 
                    pix_key = '', 
                    pix_type = 'Cpf', )
            )
        else:
            return PostWithdraws200Response(
                id = '',
                external_id = '',
                external_integration_key = '',
                external_integration_id = '',
                cost_fee = 1.337,
                status = 'Pending',
                error_code = '',
                error_message = '',
                payed_at = None,
                payout_account = payconductor-sdk.models.post_withdraws_200_response_payout_account.postWithdraws_200_response_payoutAccount(
                    id = '', 
                    owner_document = '48072888001528', 
                    owner_name = '', 
                    pix_key = '', 
                    pix_type = 'Cpf', ),
        )
        """

    def testPostWithdraws200Response(self):
        """Test PostWithdraws200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
