/**
 * PayConductor API
 * PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerchantInput from './MerchantInput';
import PostWithdrawsRequestPayoutAccount from './PostWithdrawsRequestPayoutAccount';

/**
 * The PostWithdrawsRequest model module.
 * @module model/PostWithdrawsRequest
 * @version 1.0.0
 */
class PostWithdrawsRequest {
    /**
     * Constructs a new <code>PostWithdrawsRequest</code>.
     * @alias module:model/PostWithdrawsRequest
     * @param amount {Number} Withdrawal amount in cents
     * @param payoutAccount {module:model/PostWithdrawsRequestPayoutAccount} 
     */
    constructor(amount, payoutAccount) { 
        
        PostWithdrawsRequest.initialize(this, amount, payoutAccount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, payoutAccount) { 
        obj['amount'] = amount;
        obj['payoutAccount'] = payoutAccount;
    }

    /**
     * Constructs a <code>PostWithdrawsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostWithdrawsRequest} obj Optional instance to populate.
     * @return {module:model/PostWithdrawsRequest} The populated <code>PostWithdrawsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostWithdrawsRequest();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('externalId')) {
                obj['externalId'] = ApiClient.convertToType(data['externalId'], 'String');
            }
            if (data.hasOwnProperty('merchant')) {
                obj['merchant'] = MerchantInput.constructFromObject(data['merchant']);
            }
            if (data.hasOwnProperty('payoutAccount')) {
                obj['payoutAccount'] = PostWithdrawsRequestPayoutAccount.constructFromObject(data['payoutAccount']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostWithdrawsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostWithdrawsRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostWithdrawsRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['externalId'] && !(typeof data['externalId'] === 'string' || data['externalId'] instanceof String)) {
            throw new Error("Expected the field `externalId` to be a primitive type in the JSON string but got " + data['externalId']);
        }
        // validate the optional field `merchant`
        if (data['merchant']) { // data not null
          MerchantInput.validateJSON(data['merchant']);
        }
        // validate the optional field `payoutAccount`
        if (data['payoutAccount']) { // data not null
          PostWithdrawsRequestPayoutAccount.validateJSON(data['payoutAccount']);
        }

        return true;
    }


}

PostWithdrawsRequest.RequiredProperties = ["amount", "payoutAccount"];

/**
 * Withdrawal amount in cents
 * @member {Number} amount
 */
PostWithdrawsRequest.prototype['amount'] = undefined;

/**
 * Withdrawal ID in your system
 * @member {String} externalId
 */
PostWithdrawsRequest.prototype['externalId'] = undefined;

/**
 * @member {module:model/MerchantInput} merchant
 */
PostWithdrawsRequest.prototype['merchant'] = undefined;

/**
 * @member {module:model/PostWithdrawsRequestPayoutAccount} payoutAccount
 */
PostWithdrawsRequest.prototype['payoutAccount'] = undefined;






export default PostWithdrawsRequest;

