/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package payconductor-sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import payconductor-sdk.models.CreditCard
import payconductor-sdk.models.CreditCardCard
import payconductor-sdk.models.CreditCardInstallments

class CreditCardTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreditCard
        //val modelInstance = CreditCard()

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `card`
        should("test card") {
            // uncomment below to test the property
            //modelInstance.card shouldBe ("TODO")
        }

        // to test the property `installments`
        should("test installments") {
            // uncomment below to test the property
            //modelInstance.installments shouldBe ("TODO")
        }

        // to test the property `softDescriptor` - Text that will appear on the card statement (soft descriptor)
        should("test softDescriptor") {
            // uncomment below to test the property
            //modelInstance.softDescriptor shouldBe ("TODO")
        }

    }
}
