/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package payconductor-sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import payconductor-sdk.models.Customer2DocumentType

class Customer2DocumentTypeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Customer2DocumentType
        //val modelInstance = Customer2DocumentType()

    }
}
