# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Cliente")

model_instance <- Cliente$new()

test_that("address", {
  # tests for the property `address` (EndereODoCliente)

  # uncomment below to test the property
  #expect_equal(model.instance$`address`, "EXPECTED_RESULT")
})

test_that("documentNumber", {
  # tests for the property `documentNumber` (character)
  # CPF ou CNPJ do cliente sem formatação

  # uncomment below to test the property
  #expect_equal(model.instance$`documentNumber`, "EXPECTED_RESULT")
})

test_that("documentType", {
  # tests for the property `documentType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`documentType`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)
  # Email do cliente

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Nome completo do cliente

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("phoneNumber", {
  # tests for the property `phoneNumber` (character)
  # Número de telefone do cliente no formato +55 DD 9XXXXXXXX

  # uncomment below to test the property
  #expect_equal(model.instance$`phoneNumber`, "EXPECTED_RESULT")
})
