# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PostOrders200ResponseCreditCard")

model_instance <- PostOrders200ResponseCreditCard$new()

test_that("authorizationCode", {
  # tests for the property `authorizationCode` (character)
  # Transaction authorization code

  # uncomment below to test the property
  #expect_equal(model.instance$`authorizationCode`, "EXPECTED_RESULT")
})
