# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CustomersApi")

api_instance <- CustomersApi$new()

test_that("DeleteCustomersById", {
  # tests for DeleteCustomersById
  # base path: https://app.payconductor.ai/api/v1
  # @param id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetCustomers", {
  # tests for GetCustomers
  # base path: https://app.payconductor.ai/api/v1
  # @param page numeric 
  # @param page_size numeric 
  # @param period character 
  # @param email character  (optional)
  # @param name character  (optional)
  # @param end_date character  (optional)
  # @param start_date character  (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetCustomersById", {
  # tests for GetCustomersById
  # base path: https://app.payconductor.ai/api/v1
  # @param id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PatchCustomersById", {
  # tests for PatchCustomersById
  # base path: https://app.payconductor.ai/api/v1
  # @param id character 
  # @param customer1 Customer1 Schema for creating a new customer
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostCustomers", {
  # tests for PostCustomers
  # base path: https://app.payconductor.ai/api/v1
  # @param customer Customer Schema for creating a new customer
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
