# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PostOrdersRequest")

model_instance <- PostOrdersRequest$new()

test_that("chargeAmount", {
  # tests for the property `chargeAmount` (numeric)
  # Total amount to be charged on the order in floating point value

  # uncomment below to test the property
  #expect_equal(model.instance$`chargeAmount`, "EXPECTED_RESULT")
})

test_that("clientIp", {
  # tests for the property `clientIp` (character)
  # Client IP address

  # uncomment below to test the property
  #expect_equal(model.instance$`clientIp`, "EXPECTED_RESULT")
})

test_that("customer", {
  # tests for the property `customer` (Customer)

  # uncomment below to test the property
  #expect_equal(model.instance$`customer`, "EXPECTED_RESULT")
})

test_that("discountAmount", {
  # tests for the property `discountAmount` (numeric)
  # Discount amount

  # uncomment below to test the property
  #expect_equal(model.instance$`discountAmount`, "EXPECTED_RESULT")
})

test_that("externalId", {
  # tests for the property `externalId` (character)
  # Order ID in your system

  # uncomment below to test the property
  #expect_equal(model.instance$`externalId`, "EXPECTED_RESULT")
})

test_that("fingerprints", {
  # tests for the property `fingerprints` (PostOrdersRequestFingerprints)

  # uncomment below to test the property
  #expect_equal(model.instance$`fingerprints`, "EXPECTED_RESULT")
})

test_that("items", {
  # tests for the property `items` (array[PostOrdersRequestItemsInner])
  # List of products or services in the order

  # uncomment below to test the property
  #expect_equal(model.instance$`items`, "EXPECTED_RESULT")
})

test_that("merchant", {
  # tests for the property `merchant` (MerchantInput)

  # uncomment below to test the property
  #expect_equal(model.instance$`merchant`, "EXPECTED_RESULT")
})

test_that("payment", {
  # tests for the property `payment` (PostOrdersRequestPayment)

  # uncomment below to test the property
  #expect_equal(model.instance$`payment`, "EXPECTED_RESULT")
})

test_that("splitAmountTotal", {
  # tests for the property `splitAmountTotal` (numeric)
  # Total split amount to be paid to the merchant (Used only for reporting purposes, does not generate actual split)

  # uncomment below to test the property
  #expect_equal(model.instance$`splitAmountTotal`, "EXPECTED_RESULT")
})

test_that("session", {
  # tests for the property `session` (PostOrdersRequestSession)

  # uncomment below to test the property
  #expect_equal(model.instance$`session`, "EXPECTED_RESULT")
})

test_that("shippingFee", {
  # tests for the property `shippingFee` (numeric)
  # Shipping fee

  # uncomment below to test the property
  #expect_equal(model.instance$`shippingFee`, "EXPECTED_RESULT")
})

test_that("taxFee", {
  # tests for the property `taxFee` (numeric)
  # Additional fees

  # uncomment below to test the property
  #expect_equal(model.instance$`taxFee`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (object)
  # Additional metadata for the order as key-value pairs. Keys should not contain spaces or special characters

  # uncomment below to test the property
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})
