// <auto-generated>
/*
 * PayConductor API
 *
 * # Introdução  Esta documentação cobre todas as funcionalidades disponíveis na API RESTful do PayConductor, incluindo autenticação, gerenciamento de recursos e exemplos de uso.  <br />  <br />  - -- -  <br />   # Autenticação  A API do PayConductor utiliza autenticação HTTP Basic para validar requisições. Você precisa fornecer suas credenciais (Client ID e Client Secret) no formato `client:secret` codificado em Base64.  <br />  ## Obtendo Credenciais  1. Acesse o painel administrativo do PayConductor 2. Navegue até **Configurações > API Keys** 3. Gere um novo par de credenciais (Client ID e Client Secret) 4. Guarde o Client Secret em local seguro - ele não será exibido novamente  <br />  ## Formato de Autenticação  As credenciais devem ser enviadas no header `Authorization` usando o esquema Basic:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Exemplo em Node.js  ```javascript const clientId = 'seu_client_id'; const clientSecret = 'seu_client_secret';  // Codifica as credenciais em Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Erros de Autenticação  | Código | Descrição | |- -- -- -- -|- -- -- -- -- --| | `401`  | Credenciais inválidas ou ausentes | | `403`  | Credenciais válidas, mas sem permissão para o recurso | | `429`  | Muitas requisições (rate limit excedido) |  ### Exemplo de resposta de erro  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using payconductor-sdk.Client;

namespace payconductor-sdk.Model
{
    /// <summary>
    /// Boleto
    /// </summary>
    public partial class Boleto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Boleto" /> class.
        /// </summary>
        /// <param name="paymentMethod">paymentMethod</param>
        /// <param name="expirationInDays">expirationInDays</param>
        [JsonConstructor]
        public Boleto(string paymentMethod, Option<BoletoExpirationInDays?> expirationInDays = default)
        {
            PaymentMethod = paymentMethod;
            ExpirationInDaysOption = expirationInDays;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets PaymentMethod
        /// </summary>
        [JsonPropertyName("paymentMethod")]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// Used to track the state of ExpirationInDays
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BoletoExpirationInDays?> ExpirationInDaysOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpirationInDays
        /// </summary>
        [JsonPropertyName("expirationInDays")]
        public BoletoExpirationInDays? ExpirationInDays { get { return this.ExpirationInDaysOption; } set { this.ExpirationInDaysOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Boleto {\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("  ExpirationInDays: ").Append(ExpirationInDays).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Boleto" />
    /// </summary>
    public class BoletoJsonConverter : JsonConverter<Boleto>
    {
        /// <summary>
        /// Deserializes json to <see cref="Boleto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Boleto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> paymentMethod = default;
            Option<BoletoExpirationInDays?> expirationInDays = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "paymentMethod":
                            paymentMethod = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "expirationInDays":
                            expirationInDays = new Option<BoletoExpirationInDays?>(JsonSerializer.Deserialize<BoletoExpirationInDays>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!paymentMethod.IsSet)
                throw new ArgumentException("Property is required for class Boleto.", nameof(paymentMethod));

            if (paymentMethod.IsSet && paymentMethod.Value == null)
                throw new ArgumentNullException(nameof(paymentMethod), "Property is not nullable for class Boleto.");

            if (expirationInDays.IsSet && expirationInDays.Value == null)
                throw new ArgumentNullException(nameof(expirationInDays), "Property is not nullable for class Boleto.");

            return new Boleto(paymentMethod.Value!, expirationInDays);
        }

        /// <summary>
        /// Serializes a <see cref="Boleto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="boleto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Boleto boleto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, boleto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Boleto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="boleto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Boleto boleto, JsonSerializerOptions jsonSerializerOptions)
        {
            if (boleto.PaymentMethod == null)
                throw new ArgumentNullException(nameof(boleto.PaymentMethod), "Property is required for class Boleto.");

            if (boleto.ExpirationInDaysOption.IsSet && boleto.ExpirationInDays == null)
                throw new ArgumentNullException(nameof(boleto.ExpirationInDays), "Property is required for class Boleto.");

            writer.WriteString("paymentMethod", boleto.PaymentMethod);

            if (boleto.ExpirationInDaysOption.IsSet)
            {
                writer.WritePropertyName("expirationInDays");
                JsonSerializer.Serialize(writer, boleto.ExpirationInDays, jsonSerializerOptions);
            }
        }
    }
}
