// <auto-generated>
/*
 * PayConductor API
 *
 * # Introdução  Esta documentação cobre todas as funcionalidades disponíveis na API RESTful do PayConductor, incluindo autenticação, gerenciamento de recursos e exemplos de uso.  <br />  <br />  - -- -  <br />   # Autenticação  A API do PayConductor utiliza autenticação HTTP Basic para validar requisições. Você precisa fornecer suas credenciais (Client ID e Client Secret) no formato `client:secret` codificado em Base64.  <br />  ## Obtendo Credenciais  1. Acesse o painel administrativo do PayConductor 2. Navegue até **Configurações > API Keys** 3. Gere um novo par de credenciais (Client ID e Client Secret) 4. Guarde o Client Secret em local seguro - ele não será exibido novamente  <br />  ## Formato de Autenticação  As credenciais devem ser enviadas no header `Authorization` usando o esquema Basic:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Exemplo em Node.js  ```javascript const clientId = 'seu_client_id'; const clientSecret = 'seu_client_secret';  // Codifica as credenciais em Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Erros de Autenticação  | Código | Descrição | |- -- -- -- -|- -- -- -- -- --| | `401`  | Credenciais inválidas ou ausentes | | `403`  | Credenciais válidas, mas sem permissão para o recurso | | `429`  | Muitas requisições (rate limit excedido) |  ### Exemplo de resposta de erro  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using payconductor-sdk.Client;

namespace payconductor-sdk.Model
{
    /// <summary>
    /// PostOrders200ResponseOrderItemsInner
    /// </summary>
    public partial class PostOrders200ResponseOrderItemsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostOrders200ResponseOrderItemsInner" /> class.
        /// </summary>
        /// <param name="id">ID do item no pedido</param>
        /// <param name="name">Nome do produto/serviço</param>
        /// <param name="qty">Quantidade</param>
        /// <param name="totalAmount">Valor total do item (quantidade × preço unitário)</param>
        /// <param name="totalNetAmount">Valor líquido total do item</param>
        /// <param name="unityPrice">Preço unitário</param>
        /// <param name="externalId">ID externo do item</param>
        [JsonConstructor]
        public PostOrders200ResponseOrderItemsInner(string id, string name, decimal qty, decimal totalAmount, decimal totalNetAmount, decimal unityPrice, string? externalId = default)
        {
            Id = id;
            Name = name;
            Qty = qty;
            TotalAmount = totalAmount;
            TotalNetAmount = totalNetAmount;
            UnityPrice = unityPrice;
            ExternalId = externalId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// ID do item no pedido
        /// </summary>
        /// <value>ID do item no pedido</value>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Nome do produto/serviço
        /// </summary>
        /// <value>Nome do produto/serviço</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Quantidade
        /// </summary>
        /// <value>Quantidade</value>
        [JsonPropertyName("qty")]
        public decimal Qty { get; set; }

        /// <summary>
        /// Valor total do item (quantidade × preço unitário)
        /// </summary>
        /// <value>Valor total do item (quantidade × preço unitário)</value>
        [JsonPropertyName("totalAmount")]
        public decimal TotalAmount { get; set; }

        /// <summary>
        /// Valor líquido total do item
        /// </summary>
        /// <value>Valor líquido total do item</value>
        [JsonPropertyName("totalNetAmount")]
        public decimal TotalNetAmount { get; set; }

        /// <summary>
        /// Preço unitário
        /// </summary>
        /// <value>Preço unitário</value>
        [JsonPropertyName("unityPrice")]
        public decimal UnityPrice { get; set; }

        /// <summary>
        /// ID externo do item
        /// </summary>
        /// <value>ID externo do item</value>
        [JsonPropertyName("externalId")]
        public string? ExternalId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostOrders200ResponseOrderItemsInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Qty: ").Append(Qty).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  TotalNetAmount: ").Append(TotalNetAmount).Append("\n");
            sb.Append("  UnityPrice: ").Append(UnityPrice).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostOrders200ResponseOrderItemsInner" />
    /// </summary>
    public class PostOrders200ResponseOrderItemsInnerJsonConverter : JsonConverter<PostOrders200ResponseOrderItemsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostOrders200ResponseOrderItemsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostOrders200ResponseOrderItemsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> name = default;
            Option<decimal?> qty = default;
            Option<decimal?> totalAmount = default;
            Option<decimal?> totalNetAmount = default;
            Option<decimal?> unityPrice = default;
            Option<string?> externalId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "qty":
                            qty = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "totalAmount":
                            totalAmount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "totalNetAmount":
                            totalNetAmount = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "unityPrice":
                            unityPrice = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "externalId":
                            externalId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class PostOrders200ResponseOrderItemsInner.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class PostOrders200ResponseOrderItemsInner.", nameof(name));

            if (!qty.IsSet)
                throw new ArgumentException("Property is required for class PostOrders200ResponseOrderItemsInner.", nameof(qty));

            if (!totalAmount.IsSet)
                throw new ArgumentException("Property is required for class PostOrders200ResponseOrderItemsInner.", nameof(totalAmount));

            if (!totalNetAmount.IsSet)
                throw new ArgumentException("Property is required for class PostOrders200ResponseOrderItemsInner.", nameof(totalNetAmount));

            if (!unityPrice.IsSet)
                throw new ArgumentException("Property is required for class PostOrders200ResponseOrderItemsInner.", nameof(unityPrice));

            if (!externalId.IsSet)
                throw new ArgumentException("Property is required for class PostOrders200ResponseOrderItemsInner.", nameof(externalId));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class PostOrders200ResponseOrderItemsInner.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class PostOrders200ResponseOrderItemsInner.");

            if (qty.IsSet && qty.Value == null)
                throw new ArgumentNullException(nameof(qty), "Property is not nullable for class PostOrders200ResponseOrderItemsInner.");

            if (totalAmount.IsSet && totalAmount.Value == null)
                throw new ArgumentNullException(nameof(totalAmount), "Property is not nullable for class PostOrders200ResponseOrderItemsInner.");

            if (totalNetAmount.IsSet && totalNetAmount.Value == null)
                throw new ArgumentNullException(nameof(totalNetAmount), "Property is not nullable for class PostOrders200ResponseOrderItemsInner.");

            if (unityPrice.IsSet && unityPrice.Value == null)
                throw new ArgumentNullException(nameof(unityPrice), "Property is not nullable for class PostOrders200ResponseOrderItemsInner.");

            return new PostOrders200ResponseOrderItemsInner(id.Value!, name.Value!, qty.Value!.Value!, totalAmount.Value!.Value!, totalNetAmount.Value!.Value!, unityPrice.Value!.Value!, externalId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PostOrders200ResponseOrderItemsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postOrders200ResponseOrderItemsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostOrders200ResponseOrderItemsInner postOrders200ResponseOrderItemsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postOrders200ResponseOrderItemsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostOrders200ResponseOrderItemsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postOrders200ResponseOrderItemsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostOrders200ResponseOrderItemsInner postOrders200ResponseOrderItemsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postOrders200ResponseOrderItemsInner.Id == null)
                throw new ArgumentNullException(nameof(postOrders200ResponseOrderItemsInner.Id), "Property is required for class PostOrders200ResponseOrderItemsInner.");

            if (postOrders200ResponseOrderItemsInner.Name == null)
                throw new ArgumentNullException(nameof(postOrders200ResponseOrderItemsInner.Name), "Property is required for class PostOrders200ResponseOrderItemsInner.");

            writer.WriteString("id", postOrders200ResponseOrderItemsInner.Id);

            writer.WriteString("name", postOrders200ResponseOrderItemsInner.Name);

            writer.WriteNumber("qty", postOrders200ResponseOrderItemsInner.Qty);

            writer.WriteNumber("totalAmount", postOrders200ResponseOrderItemsInner.TotalAmount);

            writer.WriteNumber("totalNetAmount", postOrders200ResponseOrderItemsInner.TotalNetAmount);

            writer.WriteNumber("unityPrice", postOrders200ResponseOrderItemsInner.UnityPrice);

            if (postOrders200ResponseOrderItemsInner.ExternalId != null)
                writer.WriteString("externalId", postOrders200ResponseOrderItemsInner.ExternalId);
            else
                writer.WriteNull("externalId");
        }
    }
}
