/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package payconductor-sdk.models

import payconductor-sdk.models.BankSlipExpirationInDays

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param paymentMethod 
 * @param expirationInDays 
 */


data class BankSlip (

    @Json(name = "paymentMethod")
    val paymentMethod: kotlin.String,

    @Json(name = "expirationInDays")
    val expirationInDays: BankSlipExpirationInDays? = null

) {


}

