/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package payconductor-sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Document type: Cpf or Cnpj
 *
 */


class Customer2DocumentType (

) {


}

