/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package payconductor-sdk.models

import payconductor-sdk.models.NuPayNuPay

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param paymentMethod 
 * @param nuPay 
 */


data class NuPay (

    @Json(name = "paymentMethod")
    val paymentMethod: kotlin.String,

    @Json(name = "nuPay")
    val nuPay: NuPayNuPay

) {


}

