=begin comment

PayConductor API

PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::PostOrders200Response;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use WWW::OpenAPIClient::Object::PostOrders200ResponseBankSlip;
use WWW::OpenAPIClient::Object::PostOrders200ResponseCreditCard;
use WWW::OpenAPIClient::Object::PostOrders200ResponseNuPay;
use WWW::OpenAPIClient::Object::PostOrders200ResponseOrderItemsInner;
use WWW::OpenAPIClient::Object::PostOrders200ResponsePicPay;
use WWW::OpenAPIClient::Object::PostOrders200ResponsePix;
use WWW::OpenAPIClient::Object::PostOrders200ResponseSession;

use base ("Class::Accessor", "Class::Data::Inheritable");

#
#
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

PayConductor API

PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {});
__PACKAGE__->mk_classdata('class_documentation' => {});

# new plain object
sub new {
    my ($class, %args) = @_;

    my $self = bless {}, $class;

    $self->init(%args);

    return $self;
}

# initialize the object
sub init
{
    my ($self, %args) = @_;

    foreach my $attribute (keys %{$self->attribute_map}) {
        my $args_key = $self->attribute_map->{$attribute};
        $self->$attribute( $args{ $args_key } );
    }
}

# return perl hash
sub to_hash {
    my $self = shift;
    my $_hash = decode_json(JSON->new->convert_blessed->encode($self));

    return $_hash;
}

# used by JSON for serialization
sub TO_JSON {
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            my $_json_attribute = $self->attribute_map->{$_key};
            my $_type = $self->openapi_types->{$_key};
            my $_value = $self->{$_key};
            if ($_type =~ /^array\[(.+)\]$/i) { # array
                my $_subclass = $1;
                $_data->{$_json_attribute} =  [ map { $self->_to_json_primitives($_subclass, $_) } @$_value ];
            } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
                my $_subclass = $1;
                my %_hash = ();
                while (my($_key, $_element) = each %{$_value}) {
                    $_hash{$_key} = $self->_to_json_primitives($_subclass, $_element);
                }
                $_data->{$_json_attribute} = \%_hash;
            } elsif ( grep( /^$_type$/, ('int', 'double', 'string', 'boolean', 'DATE', 'DATE_TIME'))) {
                $_data->{$_json_attribute} = $self->_to_json_primitives($_type, $_value);
            } else {
                $_data->{$_json_attribute} = $_value;
            }
        }
    }

    return $_data;
}

# to_json non-array data
sub _to_json_primitives {
    my ($self, $type, $data) = @_;
    if ( grep( /^$type$/, ('int', 'double'))) {
        # https://metacpan.org/pod/JSON#simple-scalars
        # numify it, ensuring it will be dumped as a number
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        # https://metacpan.org/pod/JSON#simple-scalars
        # stringified
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        # https://metacpan.org/pod/JSON#JSON::true,-JSON::false,-JSON::null
        return $data ? \1 : \0;
    } elsif ($type eq 'DATE') {
        return undef unless defined $data;
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Eymd($optional_separator),-$dt-%3Emdy(...),-$dt-%3Edmy(...)
            return $data->ymd;
        }
        return $data .q();
    } elsif ($type eq 'DATE_TIME') {
        return undef unless defined $data;
        # the date-time notation as defined by RFC 3339, section 5.6, for example, 2017-07-21T17:32:28Z
        if (ref($data) eq 'DateTime') {
            # https://metacpan.org/pod/DateTime#$dt-%3Erfc3339
            return $data->rfc3339;
        }
        return $data .q();
    } else { # hash (model),  In this case, the TO_JSON of the $data object is executed
        return $data;
    }
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
        my $_json_attribute = $self->attribute_map->{$_key};
        if ($_type =~ /^array\[(.+)\]$/i) { # array
            my $_subclass = $1;
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif ($_type =~ /^hash\[string,(.+)\]$/i) { # hash
            my $_subclass = $1;
            my %_hash = ();
            while (my($_key, $_element) = each %{$hash->{$_json_attribute}}) {
                $_hash{$_key} = $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \%_hash;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
            $log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }

    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);

    if (grep( /^$type$/ , ('DATE_TIME', 'DATE'))) {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double'))) {
        return undef unless defined $data;
        return $data + 0;
    } elsif ($type eq 'string') {
        return undef unless defined $data;
        return $data . q();
    } elsif ($type eq 'boolean') {
        return !!$data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}


__PACKAGE__->class_documentation({description => '',
                                  class => 'PostOrders200Response',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'id' => {
        datatype => 'string',
        base_name => 'id',
        description => 'Order ID in the system',
        format => '',
        read_only => '',
            },
    'external_id' => {
        datatype => 'string',
        base_name => 'externalId',
        description => 'External order ID (provided by your integration)',
        format => '',
        read_only => '',
            },
    'external_integration_key' => {
        datatype => 'string',
        base_name => 'externalIntegrationKey',
        description => 'Provider used to process the order',
        format => '',
        read_only => '',
            },
    'external_integration_id' => {
        datatype => 'string',
        base_name => 'externalIntegrationId',
        description => 'Order ID in the payment provider',
        format => '',
        read_only => '',
            },
    'amount' => {
        datatype => 'double',
        base_name => 'amount',
        description => 'Total order amount',
        format => '',
        read_only => '',
            },
    'cost_fee' => {
        datatype => 'double',
        base_name => 'costFee',
        description => 'Cost fee applied to the order',
        format => '',
        read_only => '',
            },
    'pix' => {
        datatype => 'PostOrders200ResponsePix',
        base_name => 'pix',
        description => '',
        format => '',
        read_only => '',
            },
    'bank_slip' => {
        datatype => 'PostOrders200ResponseBankSlip',
        base_name => 'bankSlip',
        description => '',
        format => '',
        read_only => '',
            },
    'nu_pay' => {
        datatype => 'PostOrders200ResponseNuPay',
        base_name => 'nuPay',
        description => '',
        format => '',
        read_only => '',
            },
    'pic_pay' => {
        datatype => 'PostOrders200ResponsePicPay',
        base_name => 'picPay',
        description => '',
        format => '',
        read_only => '',
            },
    'credit_card' => {
        datatype => 'PostOrders200ResponseCreditCard',
        base_name => 'creditCard',
        description => '',
        format => '',
        read_only => '',
            },
    'status' => {
        datatype => 'string',
        base_name => 'status',
        description => '',
        format => '',
        read_only => '',
            },
    'payment_method' => {
        datatype => 'string',
        base_name => 'paymentMethod',
        description => '',
        format => '',
        read_only => '',
            },
    'payed_at' => {
        datatype => 'string',
        base_name => 'payedAt',
        description => 'Date and time when the order was paid (ISO 8601)',
        format => '',
        read_only => '',
            },
    'error_code' => {
        datatype => 'string',
        base_name => 'errorCode',
        description => 'Error code, if any',
        format => '',
        read_only => '',
            },
    'error_message' => {
        datatype => 'string',
        base_name => 'errorMessage',
        description => 'Error message, if any',
        format => '',
        read_only => '',
            },
    'order_items' => {
        datatype => 'ARRAY[PostOrders200ResponseOrderItemsInner]',
        base_name => 'orderItems',
        description => '',
        format => '',
        read_only => '',
            },
    'session' => {
        datatype => 'PostOrders200ResponseSession',
        base_name => 'session',
        description => '',
        format => '',
        read_only => '',
            },
});

__PACKAGE__->openapi_types( {
    'id' => 'string',
    'external_id' => 'string',
    'external_integration_key' => 'string',
    'external_integration_id' => 'string',
    'amount' => 'double',
    'cost_fee' => 'double',
    'pix' => 'PostOrders200ResponsePix',
    'bank_slip' => 'PostOrders200ResponseBankSlip',
    'nu_pay' => 'PostOrders200ResponseNuPay',
    'pic_pay' => 'PostOrders200ResponsePicPay',
    'credit_card' => 'PostOrders200ResponseCreditCard',
    'status' => 'string',
    'payment_method' => 'string',
    'payed_at' => 'string',
    'error_code' => 'string',
    'error_message' => 'string',
    'order_items' => 'ARRAY[PostOrders200ResponseOrderItemsInner]',
    'session' => 'PostOrders200ResponseSession'
} );

__PACKAGE__->attribute_map( {
    'id' => 'id',
    'external_id' => 'externalId',
    'external_integration_key' => 'externalIntegrationKey',
    'external_integration_id' => 'externalIntegrationId',
    'amount' => 'amount',
    'cost_fee' => 'costFee',
    'pix' => 'pix',
    'bank_slip' => 'bankSlip',
    'nu_pay' => 'nuPay',
    'pic_pay' => 'picPay',
    'credit_card' => 'creditCard',
    'status' => 'status',
    'payment_method' => 'paymentMethod',
    'payed_at' => 'payedAt',
    'error_code' => 'errorCode',
    'error_message' => 'errorMessage',
    'order_items' => 'orderItems',
    'session' => 'session'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
