# coding: utf-8

"""
    PayConductor API

    PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from payconductor-sdk.models.post_orders200_response_bank_slip import PostOrders200ResponseBankSlip
from payconductor-sdk.models.post_orders200_response_credit_card import PostOrders200ResponseCreditCard
from payconductor-sdk.models.post_orders200_response_nu_pay import PostOrders200ResponseNuPay
from payconductor-sdk.models.post_orders200_response_order_items_inner import PostOrders200ResponseOrderItemsInner
from payconductor-sdk.models.post_orders200_response_pic_pay import PostOrders200ResponsePicPay
from payconductor-sdk.models.post_orders200_response_pix import PostOrders200ResponsePix
from payconductor-sdk.models.post_orders200_response_session import PostOrders200ResponseSession
from typing import Optional, Set
from typing_extensions import Self

class PostOrders200Response(BaseModel):
    """
    PostOrders200Response
    """ # noqa: E501
    id: StrictStr = Field(description="Order ID in the system")
    external_id: Optional[StrictStr] = Field(description="External order ID (provided by your integration)", alias="externalId")
    external_integration_key: StrictStr = Field(description="Provider used to process the order", alias="externalIntegrationKey")
    external_integration_id: Optional[StrictStr] = Field(description="Order ID in the payment provider", alias="externalIntegrationId")
    amount: Union[StrictFloat, StrictInt] = Field(description="Total order amount")
    cost_fee: Union[StrictFloat, StrictInt] = Field(description="Cost fee applied to the order", alias="costFee")
    pix: Optional[PostOrders200ResponsePix] = None
    bank_slip: Optional[PostOrders200ResponseBankSlip] = Field(default=None, alias="bankSlip")
    nu_pay: Optional[PostOrders200ResponseNuPay] = Field(default=None, alias="nuPay")
    pic_pay: Optional[PostOrders200ResponsePicPay] = Field(default=None, alias="picPay")
    credit_card: Optional[PostOrders200ResponseCreditCard] = Field(default=None, alias="creditCard")
    status: StrictStr
    payment_method: StrictStr = Field(alias="paymentMethod")
    payed_at: Optional[StrictStr] = Field(description="Date and time when the order was paid (ISO 8601)", alias="payedAt")
    error_code: Optional[StrictStr] = Field(description="Error code, if any", alias="errorCode")
    error_message: Optional[StrictStr] = Field(description="Error message, if any", alias="errorMessage")
    order_items: List[PostOrders200ResponseOrderItemsInner] = Field(alias="orderItems")
    session: Optional[PostOrders200ResponseSession] = None
    __properties: ClassVar[List[str]] = ["id", "externalId", "externalIntegrationKey", "externalIntegrationId", "amount", "costFee", "pix", "bankSlip", "nuPay", "picPay", "creditCard", "status", "paymentMethod", "payedAt", "errorCode", "errorMessage", "orderItems", "session"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Generating', 'Pending', 'Completed', 'Failed', 'Canceled', 'Refunding', 'Refunded', 'InDispute', 'Chargeback']):
            raise ValueError("must be one of enum values ('Generating', 'Pending', 'Completed', 'Failed', 'Canceled', 'Refunding', 'Refunded', 'InDispute', 'Chargeback')")
        return value

    @field_validator('payment_method')
    def payment_method_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Pix', 'CreditCard', 'DebitCard', 'BankSlip', 'Crypto', 'ApplePay', 'NuPay', 'PicPay', 'AmazonPay', 'SepaDebit', 'GooglePay']):
            raise ValueError("must be one of enum values ('Pix', 'CreditCard', 'DebitCard', 'BankSlip', 'Crypto', 'ApplePay', 'NuPay', 'PicPay', 'AmazonPay', 'SepaDebit', 'GooglePay')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostOrders200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pix
        if self.pix:
            _dict['pix'] = self.pix.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bank_slip
        if self.bank_slip:
            _dict['bankSlip'] = self.bank_slip.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nu_pay
        if self.nu_pay:
            _dict['nuPay'] = self.nu_pay.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pic_pay
        if self.pic_pay:
            _dict['picPay'] = self.pic_pay.to_dict()
        # override the default output from pydantic by calling `to_dict()` of credit_card
        if self.credit_card:
            _dict['creditCard'] = self.credit_card.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in order_items (list)
        _items = []
        if self.order_items:
            for _item_order_items in self.order_items:
                if _item_order_items:
                    _items.append(_item_order_items.to_dict())
            _dict['orderItems'] = _items
        # override the default output from pydantic by calling `to_dict()` of session
        if self.session:
            _dict['session'] = self.session.to_dict()
        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['externalId'] = None

        # set to None if external_integration_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_integration_id is None and "external_integration_id" in self.model_fields_set:
            _dict['externalIntegrationId'] = None

        # set to None if payed_at (nullable) is None
        # and model_fields_set contains the field
        if self.payed_at is None and "payed_at" in self.model_fields_set:
            _dict['payedAt'] = None

        # set to None if error_code (nullable) is None
        # and model_fields_set contains the field
        if self.error_code is None and "error_code" in self.model_fields_set:
            _dict['errorCode'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['errorMessage'] = None

        # set to None if session (nullable) is None
        # and model_fields_set contains the field
        if self.session is None and "session" in self.model_fields_set:
            _dict['session'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostOrders200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "externalId": obj.get("externalId"),
            "externalIntegrationKey": obj.get("externalIntegrationKey"),
            "externalIntegrationId": obj.get("externalIntegrationId"),
            "amount": obj.get("amount"),
            "costFee": obj.get("costFee"),
            "pix": PostOrders200ResponsePix.from_dict(obj["pix"]) if obj.get("pix") is not None else None,
            "bankSlip": PostOrders200ResponseBankSlip.from_dict(obj["bankSlip"]) if obj.get("bankSlip") is not None else None,
            "nuPay": PostOrders200ResponseNuPay.from_dict(obj["nuPay"]) if obj.get("nuPay") is not None else None,
            "picPay": PostOrders200ResponsePicPay.from_dict(obj["picPay"]) if obj.get("picPay") is not None else None,
            "creditCard": PostOrders200ResponseCreditCard.from_dict(obj["creditCard"]) if obj.get("creditCard") is not None else None,
            "status": obj.get("status"),
            "paymentMethod": obj.get("paymentMethod"),
            "payedAt": obj.get("payedAt"),
            "errorCode": obj.get("errorCode"),
            "errorMessage": obj.get("errorMessage"),
            "orderItems": [PostOrders200ResponseOrderItemsInner.from_dict(_item) for _item in obj["orderItems"]] if obj.get("orderItems") is not None else None,
            "session": PostOrders200ResponseSession.from_dict(obj["session"]) if obj.get("session") is not None else None
        })
        return _obj


