# coding: utf-8

"""
    PayConductor API

    # Introdução  Esta documentação cobre todas as funcionalidades disponíveis na API RESTful do PayConductor, incluindo autenticação, gerenciamento de recursos e exemplos de uso.  <br />  <br />  ----  <br />   # Autenticação  A API do PayConductor utiliza autenticação HTTP Basic para validar requisições. Você precisa fornecer suas credenciais (Client ID e Client Secret) no formato `client:secret` codificado em Base64.  <br />  ## Obtendo Credenciais  1. Acesse o painel administrativo do PayConductor 2. Navegue até **Configurações > API Keys** 3. Gere um novo par de credenciais (Client ID e Client Secret) 4. Guarde o Client Secret em local seguro - ele não será exibido novamente  <br />  ## Formato de Autenticação  As credenciais devem ser enviadas no header `Authorization` usando o esquema Basic:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Exemplo em Node.js  ```javascript const clientId = 'seu_client_id'; const clientSecret = 'seu_client_secret';  // Codifica as credenciais em Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Erros de Autenticação  | Código | Descrição | |--------|-----------| | `401`  | Credenciais inválidas ou ausentes | | `403`  | Credenciais válidas, mas sem permissão para o recurso | | `429`  | Muitas requisições (rate limit excedido) |  ### Exemplo de resposta de erro  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from payconductor-sdk.models.boleto import Boleto
from payconductor-sdk.models.cart_ode_cr_dito import CartODeCrDito
from payconductor-sdk.models.nu_pay import NuPay
from payconductor-sdk.models.pic_pay import PicPay
from payconductor-sdk.models.pix import Pix
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

POSTORDERSREQUESTPAYMENT_ANY_OF_SCHEMAS = ["Boleto", "CartODeCrDito", "NuPay", "PicPay", "Pix"]

class PostOrdersRequestPayment(BaseModel):
    """
    Dados de pagamento para o pedido (Pix, Cartão de Crédito, Boleto, NuPay, etc...)
    """

    # data type: Pix
    anyof_schema_1_validator: Optional[Pix] = None
    # data type: CartODeCrDito
    anyof_schema_2_validator: Optional[CartODeCrDito] = None
    # data type: Boleto
    anyof_schema_3_validator: Optional[Boleto] = None
    # data type: NuPay
    anyof_schema_4_validator: Optional[NuPay] = None
    # data type: PicPay
    anyof_schema_5_validator: Optional[PicPay] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[Boleto, CartODeCrDito, NuPay, PicPay, Pix]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "Boleto", "CartODeCrDito", "NuPay", "PicPay", "Pix" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = PostOrdersRequestPayment.model_construct()
        error_messages = []
        # validate data type: Pix
        if not isinstance(v, Pix):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Pix`")
        else:
            return v

        # validate data type: CartODeCrDito
        if not isinstance(v, CartODeCrDito):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CartODeCrDito`")
        else:
            return v

        # validate data type: Boleto
        if not isinstance(v, Boleto):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Boleto`")
        else:
            return v

        # validate data type: NuPay
        if not isinstance(v, NuPay):
            error_messages.append(f"Error! Input type `{type(v)}` is not `NuPay`")
        else:
            return v

        # validate data type: PicPay
        if not isinstance(v, PicPay):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PicPay`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in PostOrdersRequestPayment with anyOf schemas: Boleto, CartODeCrDito, NuPay, PicPay, Pix. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[Pix] = None
        try:
            instance.actual_instance = Pix.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[CartODeCrDito] = None
        try:
            instance.actual_instance = CartODeCrDito.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[Boleto] = None
        try:
            instance.actual_instance = Boleto.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[NuPay] = None
        try:
            instance.actual_instance = NuPay.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[PicPay] = None
        try:
            instance.actual_instance = PicPay.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PostOrdersRequestPayment with anyOf schemas: Boleto, CartODeCrDito, NuPay, PicPay, Pix. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], Boleto, CartODeCrDito, NuPay, PicPay, Pix]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


