# coding: utf-8

"""
    PayConductor API

    PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class PostWithdraws200ResponsePayoutAccount(BaseModel):
    """
    PostWithdraws200ResponsePayoutAccount
    """ # noqa: E501
    id: StrictStr = Field(description="Unique payment account identifier")
    owner_document: Annotated[str, Field(strict=True)] = Field(description="Account holder document (CPF or CNPJ)", alias="ownerDocument")
    owner_name: StrictStr = Field(description="Account holder name", alias="ownerName")
    pix_key: StrictStr = Field(description="PIX key used for the withdrawal", alias="pixKey")
    pix_type: StrictStr = Field(description="PIX key type", alias="pixType")
    __properties: ClassVar[List[str]] = ["id", "ownerDocument", "ownerName", "pixKey", "pixType"]

    @field_validator('owner_document')
    def owner_document_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^\d{11}$|^\d{14}$", value):
            raise ValueError(r"must validate the regular expression /^\d{11}$|^\d{14}$/")
        return value

    @field_validator('pix_type')
    def pix_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Cpf', 'Cnpj', 'Email', 'Phone', 'Random']):
            raise ValueError("must be one of enum values ('Cpf', 'Cnpj', 'Email', 'Phone', 'Random')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostWithdraws200ResponsePayoutAccount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostWithdraws200ResponsePayoutAccount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "ownerDocument": obj.get("ownerDocument"),
            "ownerName": obj.get("ownerName"),
            "pixKey": obj.get("pixKey"),
            "pixType": obj.get("pixType") if obj.get("pixType") is not None else 'Cpf'
        })
        return _obj


