# coding: utf-8

"""
    PayConductor API

    PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from payconductor-sdk.models.customer import Customer
from payconductor-sdk.models.merchant_input import MerchantInput
from payconductor-sdk.models.post_orders_request_fingerprints import PostOrdersRequestFingerprints
from payconductor-sdk.models.post_orders_request_items_inner import PostOrdersRequestItemsInner
from payconductor-sdk.models.post_orders_request_payment import PostOrdersRequestPayment
from payconductor-sdk.models.post_orders_request_session import PostOrdersRequestSession
from typing import Optional, Set
from typing_extensions import Self

class PostOrdersRequest(BaseModel):
    """
    PostOrdersRequest
    """ # noqa: E501
    charge_amount: Union[StrictFloat, StrictInt] = Field(description="Total amount to be charged on the order in floating point value", alias="chargeAmount")
    client_ip: StrictStr = Field(description="Client IP address", alias="clientIp")
    customer: Customer
    discount_amount: Union[StrictFloat, StrictInt] = Field(description="Discount amount", alias="discountAmount")
    external_id: StrictStr = Field(description="Order ID in your system", alias="externalId")
    fingerprints: Optional[PostOrdersRequestFingerprints] = None
    items: Optional[Annotated[List[PostOrdersRequestItemsInner], Field(max_length=20)]] = Field(default=None, description="List of products or services in the order")
    merchant: Optional[MerchantInput] = None
    payment: PostOrdersRequestPayment
    split_amount_total: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Total split amount to be paid to the merchant (Used only for reporting purposes, does not generate actual split)", alias="splitAmountTotal")
    session: Optional[PostOrdersRequestSession] = None
    shipping_fee: Union[StrictFloat, StrictInt] = Field(description="Shipping fee", alias="shippingFee")
    tax_fee: Union[StrictFloat, StrictInt] = Field(description="Additional fees", alias="taxFee")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Additional metadata for the order as key-value pairs. Keys should not contain spaces or special characters")
    __properties: ClassVar[List[str]] = ["chargeAmount", "clientIp", "customer", "discountAmount", "externalId", "fingerprints", "items", "merchant", "payment", "splitAmountTotal", "session", "shippingFee", "taxFee", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostOrdersRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fingerprints
        if self.fingerprints:
            _dict['fingerprints'] = self.fingerprints.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of merchant
        if self.merchant:
            _dict['merchant'] = self.merchant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of payment
        if self.payment:
            _dict['payment'] = self.payment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of session
        if self.session:
            _dict['session'] = self.session.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostOrdersRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "chargeAmount": obj.get("chargeAmount"),
            "clientIp": obj.get("clientIp"),
            "customer": Customer.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "discountAmount": obj.get("discountAmount") if obj.get("discountAmount") is not None else 0,
            "externalId": obj.get("externalId"),
            "fingerprints": PostOrdersRequestFingerprints.from_dict(obj["fingerprints"]) if obj.get("fingerprints") is not None else None,
            "items": [PostOrdersRequestItemsInner.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "merchant": MerchantInput.from_dict(obj["merchant"]) if obj.get("merchant") is not None else None,
            "payment": PostOrdersRequestPayment.from_dict(obj["payment"]) if obj.get("payment") is not None else None,
            "splitAmountTotal": obj.get("splitAmountTotal"),
            "session": PostOrdersRequestSession.from_dict(obj["session"]) if obj.get("session") is not None else None,
            "shippingFee": obj.get("shippingFee") if obj.get("shippingFee") is not None else 0,
            "taxFee": obj.get("taxFee") if obj.get("taxFee") is not None else 0,
            "metadata": obj.get("metadata")
        })
        return _obj


