/*
PayConductor API

PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payconductor-sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PicPay type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PicPay{}

// PicPay struct for PicPay
type PicPay struct {
	PaymentMethod string `json:"paymentMethod"`
}

type _PicPay PicPay

// NewPicPay instantiates a new PicPay object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPicPay(paymentMethod string) *PicPay {
	this := PicPay{}
	this.PaymentMethod = paymentMethod
	return &this
}

// NewPicPayWithDefaults instantiates a new PicPay object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPicPayWithDefaults() *PicPay {
	this := PicPay{}
	return &this
}

// GetPaymentMethod returns the PaymentMethod field value
func (o *PicPay) GetPaymentMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value
// and a boolean to check if the value has been set.
func (o *PicPay) GetPaymentMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethod, true
}

// SetPaymentMethod sets field value
func (o *PicPay) SetPaymentMethod(v string) {
	o.PaymentMethod = v
}

func (o PicPay) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PicPay) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["paymentMethod"] = o.PaymentMethod
	return toSerialize, nil
}

func (o *PicPay) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"paymentMethod",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPicPay := _PicPay{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPicPay)

	if err != nil {
		return err
	}

	*o = PicPay(varPicPay)

	return err
}

type NullablePicPay struct {
	value *PicPay
	isSet bool
}

func (v NullablePicPay) Get() *PicPay {
	return v.value
}

func (v *NullablePicPay) Set(val *PicPay) {
	v.value = val
	v.isSet = true
}

func (v NullablePicPay) IsSet() bool {
	return v.isSet
}

func (v *NullablePicPay) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePicPay(val *PicPay) *NullablePicPay {
	return &NullablePicPay{value: val, isSet: true}
}

func (v NullablePicPay) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePicPay) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


