/*
PayConductor API

# Introdução  Esta documentação cobre todas as funcionalidades disponíveis na API RESTful do PayConductor, incluindo autenticação, gerenciamento de recursos e exemplos de uso.  <br />  <br />  ----  <br />   # Autenticação  A API do PayConductor utiliza autenticação HTTP Basic para validar requisições. Você precisa fornecer suas credenciais (Client ID e Client Secret) no formato `client:secret` codificado em Base64.  <br />  ## Obtendo Credenciais  1. Acesse o painel administrativo do PayConductor 2. Navegue até **Configurações > API Keys** 3. Gere um novo par de credenciais (Client ID e Client Secret) 4. Guarde o Client Secret em local seguro - ele não será exibido novamente  <br />  ## Formato de Autenticação  As credenciais devem ser enviadas no header `Authorization` usando o esquema Basic:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Exemplo em Node.js  ```javascript const clientId = 'seu_client_id'; const clientSecret = 'seu_client_secret';  // Codifica as credenciais em Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Erros de Autenticação  | Código | Descrição | |--------|-----------| | `401`  | Credenciais inválidas ou ausentes | | `403`  | Credenciais válidas, mas sem permissão para o recurso | | `429`  | Muitas requisições (rate limit excedido) |  ### Exemplo de resposta de erro  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payconductor-sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Cliente type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cliente{}

// Cliente Schema para criação de um novo cliente
type Cliente struct {
	Address *EndereODoCliente `json:"address,omitempty"`
	// CPF ou CNPJ do cliente sem formatação
	DocumentNumber string `json:"documentNumber" validate:"regexp=^\\\\d{11}$|^\\\\d{14}$"`
	DocumentType string `json:"documentType"`
	// Email do cliente
	Email string `json:"email"`
	// Nome completo do cliente
	Name string `json:"name"`
	// Número de telefone do cliente no formato +55 DD 9XXXXXXXX
	PhoneNumber *string `json:"phoneNumber,omitempty" validate:"regexp=^\\\\+(\\\\d{1,2}) (\\\\d{2}) (\\\\d{8,9})$"`
}

type _Cliente Cliente

// NewCliente instantiates a new Cliente object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCliente(documentNumber string, documentType string, email string, name string) *Cliente {
	this := Cliente{}
	this.DocumentNumber = documentNumber
	this.DocumentType = documentType
	this.Email = email
	this.Name = name
	return &this
}

// NewClienteWithDefaults instantiates a new Cliente object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClienteWithDefaults() *Cliente {
	this := Cliente{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *Cliente) GetAddress() EndereODoCliente {
	if o == nil || IsNil(o.Address) {
		var ret EndereODoCliente
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cliente) GetAddressOk() (*EndereODoCliente, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *Cliente) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given EndereODoCliente and assigns it to the Address field.
func (o *Cliente) SetAddress(v EndereODoCliente) {
	o.Address = &v
}

// GetDocumentNumber returns the DocumentNumber field value
func (o *Cliente) GetDocumentNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentNumber
}

// GetDocumentNumberOk returns a tuple with the DocumentNumber field value
// and a boolean to check if the value has been set.
func (o *Cliente) GetDocumentNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentNumber, true
}

// SetDocumentNumber sets field value
func (o *Cliente) SetDocumentNumber(v string) {
	o.DocumentNumber = v
}

// GetDocumentType returns the DocumentType field value
func (o *Cliente) GetDocumentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentType
}

// GetDocumentTypeOk returns a tuple with the DocumentType field value
// and a boolean to check if the value has been set.
func (o *Cliente) GetDocumentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentType, true
}

// SetDocumentType sets field value
func (o *Cliente) SetDocumentType(v string) {
	o.DocumentType = v
}

// GetEmail returns the Email field value
func (o *Cliente) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *Cliente) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *Cliente) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value
func (o *Cliente) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Cliente) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Cliente) SetName(v string) {
	o.Name = v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *Cliente) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cliente) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *Cliente) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *Cliente) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

func (o Cliente) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cliente) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	toSerialize["documentNumber"] = o.DocumentNumber
	toSerialize["documentType"] = o.DocumentType
	toSerialize["email"] = o.Email
	toSerialize["name"] = o.Name
	if !IsNil(o.PhoneNumber) {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	return toSerialize, nil
}

func (o *Cliente) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"documentNumber",
		"documentType",
		"email",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCliente := _Cliente{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCliente)

	if err != nil {
		return err
	}

	*o = Cliente(varCliente)

	return err
}

type NullableCliente struct {
	value *Cliente
	isSet bool
}

func (v NullableCliente) Get() *Cliente {
	return v.value
}

func (v *NullableCliente) Set(val *Cliente) {
	v.value = val
	v.isSet = true
}

func (v NullableCliente) IsSet() bool {
	return v.isSet
}

func (v *NullableCliente) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCliente(val *Cliente) *NullableCliente {
	return &NullableCliente{value: val, isSet: true}
}

func (v NullableCliente) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCliente) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


