/*
PayConductor API

# Introdução  Esta documentação cobre todas as funcionalidades disponíveis na API RESTful do PayConductor, incluindo autenticação, gerenciamento de recursos e exemplos de uso.  <br />  <br />  ----  <br />   # Autenticação  A API do PayConductor utiliza autenticação HTTP Basic para validar requisições. Você precisa fornecer suas credenciais (Client ID e Client Secret) no formato `client:secret` codificado em Base64.  <br />  ## Obtendo Credenciais  1. Acesse o painel administrativo do PayConductor 2. Navegue até **Configurações > API Keys** 3. Gere um novo par de credenciais (Client ID e Client Secret) 4. Guarde o Client Secret em local seguro - ele não será exibido novamente  <br />  ## Formato de Autenticação  As credenciais devem ser enviadas no header `Authorization` usando o esquema Basic:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Exemplo em Node.js  ```javascript const clientId = 'seu_client_id'; const clientSecret = 'seu_client_secret';  // Codifica as credenciais em Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Erros de Autenticação  | Código | Descrição | |--------|-----------| | `401`  | Credenciais inválidas ou ausentes | | `403`  | Credenciais válidas, mas sem permissão para o recurso | | `429`  | Muitas requisições (rate limit excedido) |  ### Exemplo de resposta de erro  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payconductor-sdk

import (
	"encoding/json"
	"fmt"
)


// CartODeCrDitoInstallments Número de parcelas
type CartODeCrDitoInstallments struct {
	Int32 *int32
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *CartODeCrDitoInstallments) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Int32
	err = json.Unmarshal(data, &dst.Int32);
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			return nil // data stored in dst.Int32, return on the first match
		}
	} else {
		dst.Int32 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(CartODeCrDitoInstallments)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CartODeCrDitoInstallments) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableCartODeCrDitoInstallments struct {
	value *CartODeCrDitoInstallments
	isSet bool
}

func (v NullableCartODeCrDitoInstallments) Get() *CartODeCrDitoInstallments {
	return v.value
}

func (v *NullableCartODeCrDitoInstallments) Set(val *CartODeCrDitoInstallments) {
	v.value = val
	v.isSet = true
}

func (v NullableCartODeCrDitoInstallments) IsSet() bool {
	return v.isSet
}

func (v *NullableCartODeCrDitoInstallments) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCartODeCrDitoInstallments(val *CartODeCrDitoInstallments) *NullableCartODeCrDitoInstallments {
	return &NullableCartODeCrDitoInstallments{value: val, isSet: true}
}

func (v NullableCartODeCrDitoInstallments) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCartODeCrDitoInstallments) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


