/*
PayConductor API

# Introdução  Esta documentação cobre todas as funcionalidades disponíveis na API RESTful do PayConductor, incluindo autenticação, gerenciamento de recursos e exemplos de uso.  <br />  <br />  ----  <br />   # Autenticação  A API do PayConductor utiliza autenticação HTTP Basic para validar requisições. Você precisa fornecer suas credenciais (Client ID e Client Secret) no formato `client:secret` codificado em Base64.  <br />  ## Obtendo Credenciais  1. Acesse o painel administrativo do PayConductor 2. Navegue até **Configurações > API Keys** 3. Gere um novo par de credenciais (Client ID e Client Secret) 4. Guarde o Client Secret em local seguro - ele não será exibido novamente  <br />  ## Formato de Autenticação  As credenciais devem ser enviadas no header `Authorization` usando o esquema Basic:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Exemplo em Node.js  ```javascript const clientId = 'seu_client_id'; const clientSecret = 'seu_client_secret';  // Codifica as credenciais em Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Erros de Autenticação  | Código | Descrição | |--------|-----------| | `401`  | Credenciais inválidas ou ausentes | | `403`  | Credenciais válidas, mas sem permissão para o recurso | | `429`  | Muitas requisições (rate limit excedido) |  ### Exemplo de resposta de erro  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payconductor-sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Boleto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Boleto{}

// Boleto struct for Boleto
type Boleto struct {
	PaymentMethod string `json:"paymentMethod"`
	ExpirationInDays *BoletoExpirationInDays `json:"expirationInDays,omitempty"`
}

type _Boleto Boleto

// NewBoleto instantiates a new Boleto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBoleto(paymentMethod string) *Boleto {
	this := Boleto{}
	this.PaymentMethod = paymentMethod
	var expirationInDays BoletoExpirationInDays = 7
	this.ExpirationInDays = &expirationInDays
	return &this
}

// NewBoletoWithDefaults instantiates a new Boleto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBoletoWithDefaults() *Boleto {
	this := Boleto{}
	var expirationInDays BoletoExpirationInDays = 7
	this.ExpirationInDays = &expirationInDays
	return &this
}

// GetPaymentMethod returns the PaymentMethod field value
func (o *Boleto) GetPaymentMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value
// and a boolean to check if the value has been set.
func (o *Boleto) GetPaymentMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethod, true
}

// SetPaymentMethod sets field value
func (o *Boleto) SetPaymentMethod(v string) {
	o.PaymentMethod = v
}

// GetExpirationInDays returns the ExpirationInDays field value if set, zero value otherwise.
func (o *Boleto) GetExpirationInDays() BoletoExpirationInDays {
	if o == nil || IsNil(o.ExpirationInDays) {
		var ret BoletoExpirationInDays
		return ret
	}
	return *o.ExpirationInDays
}

// GetExpirationInDaysOk returns a tuple with the ExpirationInDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Boleto) GetExpirationInDaysOk() (*BoletoExpirationInDays, bool) {
	if o == nil || IsNil(o.ExpirationInDays) {
		return nil, false
	}
	return o.ExpirationInDays, true
}

// HasExpirationInDays returns a boolean if a field has been set.
func (o *Boleto) HasExpirationInDays() bool {
	if o != nil && !IsNil(o.ExpirationInDays) {
		return true
	}

	return false
}

// SetExpirationInDays gets a reference to the given BoletoExpirationInDays and assigns it to the ExpirationInDays field.
func (o *Boleto) SetExpirationInDays(v BoletoExpirationInDays) {
	o.ExpirationInDays = &v
}

func (o Boleto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Boleto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["paymentMethod"] = o.PaymentMethod
	if !IsNil(o.ExpirationInDays) {
		toSerialize["expirationInDays"] = o.ExpirationInDays
	}
	return toSerialize, nil
}

func (o *Boleto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"paymentMethod",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBoleto := _Boleto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBoleto)

	if err != nil {
		return err
	}

	*o = Boleto(varBoleto)

	return err
}

type NullableBoleto struct {
	value *Boleto
	isSet bool
}

func (v NullableBoleto) Get() *Boleto {
	return v.value
}

func (v *NullableBoleto) Set(val *Boleto) {
	v.value = val
	v.isSet = true
}

func (v NullableBoleto) IsSet() bool {
	return v.isSet
}

func (v *NullableBoleto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBoleto(val *Boleto) *NullableBoleto {
	return &NullableBoleto{value: val, isSet: true}
}

func (v NullableBoleto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBoleto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


