/*
PayConductor API

PayConductor API Documentation.  This documentation covers all available features in the PayConductor RESTful API, including authentication, resource management, and usage examples.  <br />  <br />  ----  <br />   # Authentication  PayConductor API uses HTTP Basic authentication to validate requests. You need to provide your credentials (Client ID and Client Secret) in the `client:secret` format encoded in Base64.  <br />  ## Getting Credentials  1. Access the PayConductor admin panel 2. Navigate to **Settings > API Keys** 3. Generate a new credentials pair (Client ID and Client Secret) 4. Store the Client Secret in a secure location - it will not be displayed again  <br />  ## Authentication Format  Credentials must be sent in the `Authorization` header using the Basic scheme:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Node.js Example  ```javascript const clientId = 'your_client_id'; const clientSecret = 'your_client_secret';  // Encode credentials in Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Authentication Errors  | Code | Description | |------|-------------| | `401` | Invalid or missing credentials | | `403` | Valid credentials but no permission for the resource | | `429` | Too many requests (rate limit exceeded) |  ### Error Response Example  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payconductor-sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostOrders200ResponseSession type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostOrders200ResponseSession{}

// PostOrders200ResponseSession struct for PostOrders200ResponseSession
type PostOrders200ResponseSession struct {
	// ID of the checkout session associated with the order
	SessionId string `json:"sessionId"`
}

type _PostOrders200ResponseSession PostOrders200ResponseSession

// NewPostOrders200ResponseSession instantiates a new PostOrders200ResponseSession object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostOrders200ResponseSession(sessionId string) *PostOrders200ResponseSession {
	this := PostOrders200ResponseSession{}
	this.SessionId = sessionId
	return &this
}

// NewPostOrders200ResponseSessionWithDefaults instantiates a new PostOrders200ResponseSession object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostOrders200ResponseSessionWithDefaults() *PostOrders200ResponseSession {
	this := PostOrders200ResponseSession{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *PostOrders200ResponseSession) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *PostOrders200ResponseSession) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *PostOrders200ResponseSession) SetSessionId(v string) {
	o.SessionId = v
}

func (o PostOrders200ResponseSession) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostOrders200ResponseSession) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sessionId"] = o.SessionId
	return toSerialize, nil
}

func (o *PostOrders200ResponseSession) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sessionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostOrders200ResponseSession := _PostOrders200ResponseSession{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostOrders200ResponseSession)

	if err != nil {
		return err
	}

	*o = PostOrders200ResponseSession(varPostOrders200ResponseSession)

	return err
}

type NullablePostOrders200ResponseSession struct {
	value *PostOrders200ResponseSession
	isSet bool
}

func (v NullablePostOrders200ResponseSession) Get() *PostOrders200ResponseSession {
	return v.value
}

func (v *NullablePostOrders200ResponseSession) Set(val *PostOrders200ResponseSession) {
	v.value = val
	v.isSet = true
}

func (v NullablePostOrders200ResponseSession) IsSet() bool {
	return v.isSet
}

func (v *NullablePostOrders200ResponseSession) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostOrders200ResponseSession(val *PostOrders200ResponseSession) *NullablePostOrders200ResponseSession {
	return &NullablePostOrders200ResponseSession{value: val, isSet: true}
}

func (v NullablePostOrders200ResponseSession) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostOrders200ResponseSession) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


