/*
PayConductor API

# Introdução  Esta documentação cobre todas as funcionalidades disponíveis na API RESTful do PayConductor, incluindo autenticação, gerenciamento de recursos e exemplos de uso.  <br />  <br />  ----  <br />   # Autenticação  A API do PayConductor utiliza autenticação HTTP Basic para validar requisições. Você precisa fornecer suas credenciais (Client ID e Client Secret) no formato `client:secret` codificado em Base64.  <br />  ## Obtendo Credenciais  1. Acesse o painel administrativo do PayConductor 2. Navegue até **Configurações > API Keys** 3. Gere um novo par de credenciais (Client ID e Client Secret) 4. Guarde o Client Secret em local seguro - ele não será exibido novamente  <br />  ## Formato de Autenticação  As credenciais devem ser enviadas no header `Authorization` usando o esquema Basic:  ``` Authorization: Basic base64(client_id:client_secret) ```  <br />  ## Exemplo em Node.js  ```javascript const clientId = 'seu_client_id'; const clientSecret = 'seu_client_secret';  // Codifica as credenciais em Base64 const credentials = Buffer.from(`${clientId}:${clientSecret}`).toString('base64');  const response = await fetch('https://api.payconductor.com/api/v1/orders', {   method: 'GET',   headers: {     'Authorization': `Basic ${credentials}`,     'Content-Type': 'application/json'   } });  const data = await response.json(); console.log(data); ```  <br />  ## Erros de Autenticação  | Código | Descrição | |--------|-----------| | `401`  | Credenciais inválidas ou ausentes | | `403`  | Credenciais válidas, mas sem permissão para o recurso | | `429`  | Muitas requisições (rate limit excedido) |  ### Exemplo de resposta de erro  ```json {   \"error\": {     \"code\": \"UNAUTHORIZED\",     \"message\": \"Invalid credentials\",     \"details\": \"The provided client ID or secret is incorrect\"   } } ```

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package payconductor-sdk

import (
	"encoding/json"
	"time"
	"fmt"
)


// PostWithdraws200ResponsePayedAt Data e hora em que o saque foi pago (formato ISO 8601)
type PostWithdraws200ResponsePayedAt struct {
	Date *Date
	Float32 *float32
	String *string
	TimeTime *time.Time
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *PostWithdraws200ResponsePayedAt) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into Date
	err = json.Unmarshal(data, &dst.Date);
	if err == nil {
		jsonDate, _ := json.Marshal(dst.Date)
		if string(jsonDate) == "{}" { // empty struct
			dst.Date = nil
		} else {
			return nil // data stored in dst.Date, return on the first match
		}
	} else {
		dst.Date = nil
	}

	// try to unmarshal JSON data into Float32
	err = json.Unmarshal(data, &dst.Float32);
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			return nil // data stored in dst.Float32, return on the first match
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	// try to unmarshal JSON data into TimeTime
	err = json.Unmarshal(data, &dst.TimeTime);
	if err == nil {
		jsonTimeTime, _ := json.Marshal(dst.TimeTime)
		if string(jsonTimeTime) == "{}" { // empty struct
			dst.TimeTime = nil
		} else {
			return nil // data stored in dst.TimeTime, return on the first match
		}
	} else {
		dst.TimeTime = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(PostWithdraws200ResponsePayedAt)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostWithdraws200ResponsePayedAt) MarshalJSON() ([]byte, error) {
	if src.Date != nil {
		return json.Marshal(&src.Date)
	}

	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	if src.TimeTime != nil {
		return json.Marshal(&src.TimeTime)
	}

	return nil, nil // no data in anyOf schemas
}


type NullablePostWithdraws200ResponsePayedAt struct {
	value *PostWithdraws200ResponsePayedAt
	isSet bool
}

func (v NullablePostWithdraws200ResponsePayedAt) Get() *PostWithdraws200ResponsePayedAt {
	return v.value
}

func (v *NullablePostWithdraws200ResponsePayedAt) Set(val *PostWithdraws200ResponsePayedAt) {
	v.value = val
	v.isSet = true
}

func (v NullablePostWithdraws200ResponsePayedAt) IsSet() bool {
	return v.isSet
}

func (v *NullablePostWithdraws200ResponsePayedAt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostWithdraws200ResponsePayedAt(val *PostWithdraws200ResponsePayedAt) *NullablePostWithdraws200ResponsePayedAt {
	return &NullablePostWithdraws200ResponsePayedAt{value: val, isSet: true}
}

func (v NullablePostWithdraws200ResponsePayedAt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostWithdraws200ResponsePayedAt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


